In [1]:
import os
from pathlib import Path
import sys

root = Path(r"C:\Users\arius\Desktop\kalshi_wnba_bot")

os.chdir(root)  # <- THIS is the key line
sys.path.insert(0, str(root / "src"))
sys.path.insert(0, str(root / "notebooks"))

print("CWD now:", Path.cwd())
import srwnba
print(srwnba.__file__)
import pandas as pd
from gridsearch_elo import run_gridsearch

CWD now: C:\Users\arius\Desktop\kalshi_wnba_bot
C:\Users\arius\Desktop\kalshi_wnba_bot\src\srwnba\__init__.py

In [2]:
import importlib
import gridsearch_elo
importlib.reload(gridsearch_elo)

from gridsearch_elo import run_gridsearch

We must tune H, K, a, and b. H=Home Court Elo Advantage, K = Learning Rate, a =  Season to season ELO retention, b = MOV strength

We gridsearch all simultaneously for robustness.

In [ ]:
initial_train_years = [2015, 2016, 2017, 2018, 2019]
all_years = list(range(2015, 2025))

H_list = [35, 40, 43, 45, 50, 55]
K_list = [10, 15, 20, 25, 30]
a_list = [0.50, 0.60, 0.70, 0.75, 0.85]

# MOV choices:
# - no MOV  -> use_mov=False (b ignored, but we'll include b=0.8 as a placeholder)
# - MOV w/ exponent -> use_mov=True and b in {0.6,0.8,1.0}
b_list = [0, 0.6, 0.8, 1.0]

train = initial_train_years.copy()
summary_rows = []

while True:
    last_train = train[-1]
    idx = all_years.index(last_train)
    if idx + 1 >= len(all_years):
        break
    test_year = all_years[idx + 1]

    print(f"\n=== WALKFORWARD: train={train[0]}-{train[-1]} test={test_year} ===")

    res = run_gridsearch(
        train_years=train,
        test_years=[test_year],
        H_list=H_list,
        K_list=K_list,
        a_list=a_list,
        b_list=b_list,
        verbose=True,
    )

    best = res.iloc[0].to_dict()
    summary_rows.append({
        "train_start": train[0],
        "train_end": train[-1],
        "test_year": test_year,
        "best_H": best["H"],
        "best_K": best["K"],
        "best_a": best["a"],
        "best_b": best["b"],
        "train_logloss": best["train_logloss"],
        "test_logloss": best["test_logloss"],
        "train_brier": best["train_brier"],
        "test_brier": best["test_brier"],
    })

    train = train + [test_year]

summary = pd.DataFrame(summary_rows)
summary

=== WALKFORWARD: train=2015-2019 test=2020 ===
H=35 K=10 a=0.5 b=0 | train_logloss=0.647221 train_brier=0.227602 | test_logloss=0.641318 test_brier=0.224553
H=35 K=10 a=0.5 b=0.6 | train_logloss=0.651598 train_brier=0.229613 | test_logloss=0.650583 test_brier=0.229021
H=35 K=10 a=0.5 b=0.8 | train_logloss=0.639823 train_brier=0.224182 | test_logloss=0.631451 test_brier=0.219773
H=35 K=10 a=0.5 b=1 | train_logloss=0.629511 train_brier=0.219728 | test_logloss=0.612255 test_brier=0.210644
H=35 K=10 a=0.6 b=0 | train_logloss=0.646402 train_brier=0.227247 | test_logloss=0.636181 test_brier=0.222111
H=35 K=10 a=0.6 b=0.6 | train_logloss=0.650554 train_brier=0.229137 | test_logloss=0.645690 test_brier=0.226660
H=35 K=10 a=0.6 b=0.8 | train_logloss=0.638927 train_brier=0.223815 | test_logloss=0.626901 test_brier=0.217627
H=35 K=10 a=0.6 b=1 | train_logloss=0.629234 train_brier=0.219669 | test_logloss=0.609631 test_brier=0.209392
H=35 K=10 a=0.7 b=0 | train_logloss=0.645936 train_brier=0.227071 | test_logloss=0.631063 test_brier=0.219722
H=35 K=10 a=0.7 b=0.6 | train_logloss=0.649789 train_brier=0.228806 | test_logloss=0.640659 test_brier=0.224269
H=35 K=10 a=0.7 b=0.8 | train_logloss=0.638469 train_brier=0.223669 | test_logloss=0.622411 test_brier=0.215551
H=35 K=10 a=0.7 b=1 | train_logloss=0.629583 train_brier=0.219899 | test_logloss=0.607436 test_brier=0.208332
H=35 K=10 a=0.75 b=0 | train_logloss=0.645860 train_brier=0.227061 | test_logloss=0.628575 test_brier=0.218582
H=35 K=10 a=0.75 b=0.6 | train_logloss=0.649537 train_brier=0.228708 | test_logloss=0.638167 test_brier=0.223106
H=35 K=10 a=0.75 b=0.8 | train_logloss=0.638440 train_brier=0.223694 | test_logloss=0.620269 test_brier=0.214583
H=35 K=10 a=0.75 b=1 | train_logloss=0.630030 train_brier=0.220134 | test_logloss=0.606557 test_brier=0.207896
H=35 K=10 a=0.85 b=0 | train_logloss=0.646084 train_brier=0.227223 | test_logloss=0.623920 test_brier=0.216510
H=35 K=10 a=0.85 b=0.6 | train_logloss=0.649365 train_brier=0.228678 | test_logloss=0.633501 test_brier=0.220989
H=35 K=10 a=0.85 b=0.8 | train_logloss=0.638879 train_brier=0.223979 | test_logloss=0.616487 test_brier=0.212936
H=35 K=10 a=0.85 b=1 | train_logloss=0.631569 train_brier=0.220873 | test_logloss=0.605418 test_brier=0.207283
H=35 K=15 a=0.5 b=0 | train_logloss=0.640420 train_brier=0.224533 | test_logloss=0.628561 test_brier=0.218450
H=35 K=15 a=0.5 b=0.6 | train_logloss=0.643923 train_brier=0.226047 | test_logloss=0.637823 test_brier=0.222839
H=35 K=15 a=0.5 b=0.8 | train_logloss=0.632828 train_brier=0.221131 | test_logloss=0.618435 test_brier=0.213588
H=35 K=15 a=0.5 b=1 | train_logloss=0.626246 train_brier=0.218438 | test_logloss=0.601583 test_brier=0.205532
H=35 K=15 a=0.6 b=0 | train_logloss=0.639762 train_brier=0.224268 | test_logloss=0.623903 test_brier=0.216275
H=35 K=15 a=0.6 b=0.6 | train_logloss=0.642978 train_brier=0.225642 | test_logloss=0.632894 test_brier=0.220499
H=35 K=15 a=0.6 b=0.8 | train_logloss=0.632305 train_brier=0.220954 | test_logloss=0.614893 test_brier=0.211929
H=35 K=15 a=0.6 b=1 | train_logloss=0.626515 train_brier=0.218593 | test_logloss=0.600682 test_brier=0.205017
H=35 K=15 a=0.7 b=0 | train_logloss=0.639509 train_brier=0.224202 | test_logloss=0.619431 test_brier=0.214226
H=35 K=15 a=0.7 b=0.6 | train_logloss=0.642413 train_brier=0.225432 | test_logloss=0.627963 test_brier=0.218201
H=35 K=15 a=0.7 b=0.8 | train_logloss=0.632325 train_brier=0.221038 | test_logloss=0.611641 test_brier=0.210421
H=35 K=15 a=0.7 b=1 | train_logloss=0.627500 train_brier=0.219054 | test_logloss=0.600446 test_brier=0.204752
H=35 K=15 a=0.75 b=0 | train_logloss=0.639557 train_brier=0.224252 | test_logloss=0.617309 test_brier=0.213271
H=35 K=15 a=0.75 b=0.6 | train_logloss=0.642306 train_brier=0.225414 | test_logloss=0.625569 test_brier=0.217110
H=35 K=15 a=0.75 b=0.8 | train_logloss=0.632576 train_brier=0.221190 | test_logloss=0.610164 test_brier=0.209744
H=35 K=15 a=0.75 b=1 | train_logloss=0.628294 train_brier=0.219405 | test_logloss=0.600610 test_brier=0.204717
H=35 K=15 a=0.85 b=0 | train_logloss=0.640056 train_brier=0.224537 | test_logloss=0.613415 test_brier=0.211562
H=35 K=15 a=0.85 b=0.6 | train_logloss=0.642522 train_brier=0.225587 | test_logloss=0.621158 test_brier=0.215165
H=35 K=15 a=0.85 b=0.8 | train_logloss=0.633650 train_brier=0.221746 | test_logloss=0.607731 test_brier=0.208641
H=35 K=15 a=0.85 b=1 | train_logloss=0.630572 train_brier=0.220365 | test_logloss=0.601629 test_brier=0.204867
H=35 K=20 a=0.5 b=0 | train_logloss=0.636505 train_brier=0.222839 | test_logloss=0.619890 test_brier=0.214341
H=35 K=20 a=0.5 b=0.6 | train_logloss=0.638596 train_brier=0.223651 | test_logloss=0.628483 test_brier=0.218369
H=35 K=20 a=0.5 b=0.8 | train_logloss=0.629088 train_brier=0.219582 | test_logloss=0.609943 test_brier=0.209574
H=35 K=20 a=0.5 b=1 | train_logloss=0.626637 train_brier=0.218599 | test_logloss=0.595853 test_brier=0.202591
H=35 K=20 a=0.6 b=0 | train_logloss=0.636019 train_brier=0.222655 | test_logloss=0.616000 test_brier=0.212543
H=35 K=20 a=0.6 b=0.6 | train_logloss=0.637821 train_brier=0.223343 | test_logloss=0.623965 test_brier=0.216246
H=35 K=20 a=0.6 b=0.8 | train_logloss=0.628901 train_brier=0.219555 | test_logloss=0.607462 test_brier=0.208394
H=35 K=20 a=0.6 b=1 | train_logloss=0.627269 train_brier=0.218865 | test_logloss=0.596175 test_brier=0.202578
H=35 K=20 a=0.7 b=0 | train_logloss=0.635960 train_brier=0.222672 | test_logloss=0.612445 test_brier=0.210924
H=35 K=20 a=0.7 b=0.6 | train_logloss=0.637494 train_brier=0.223257 | test_logloss=0.619559 test_brier=0.214216
H=35 K=20 a=0.7 b=0.8 | train_logloss=0.629314 train_brier=0.219801 | test_logloss=0.605438 test_brier=0.207413
H=35 K=20 a=0.7 b=1 | train_logloss=0.628642 train_brier=0.219426 | test_logloss=0.597326 test_brier=0.202862
H=35 K=20 a=0.75 b=0 | train_logloss=0.636109 train_brier=0.222763 | test_logloss=0.610823 test_brier=0.210195
H=35 K=20 a=0.75 b=0.6 | train_logloss=0.637531 train_brier=0.223311 | test_logloss=0.617451 test_brier=0.213264
H=35 K=20 a=0.75 b=0.8 | train_logloss=0.629779 train_brier=0.220037 | test_logloss=0.604643 test_brier=0.207013
H=35 K=20 a=0.75 b=1 | train_logloss=0.629649 train_brier=0.219826 | test_logloss=0.598250 test_brier=0.203116
H=35 K=20 a=0.85 b=0 | train_logloss=0.636810 train_brier=0.223121 | test_logloss=0.607975 test_brier=0.208931
H=35 K=20 a=0.85 b=0.6 | train_logloss=0.638097 train_brier=0.223648 | test_logloss=0.613650 test_brier=0.211599
H=35 K=20 a=0.85 b=0.8 | train_logloss=0.631320 train_brier=0.220759 | test_logloss=0.603577 test_brier=0.206421
H=35 K=20 a=0.85 b=1 | train_logloss=0.632359 train_brier=0.220866 | test_logloss=0.600874 test_brier=0.203849
H=35 K=25 a=0.5 b=0 | train_logloss=0.634401 train_brier=0.221967 | test_logloss=0.613639 test_brier=0.211375
H=35 K=25 a=0.5 b=0.6 | train_logloss=0.634835 train_brier=0.222011 | test_logloss=0.621382 test_brier=0.215000
H=35 K=25 a=0.5 b=0.8 | train_logloss=0.627292 train_brier=0.218874 | test_logloss=0.604051 test_brier=0.206764
H=35 K=25 a=0.5 b=1 | train_logloss=0.629003 train_brier=0.219454 | test_logloss=0.592981 test_brier=0.200816
H=35 K=25 a=0.6 b=0 | train_logloss=0.634066 train_brier=0.221843 | test_logloss=0.610511 test_brier=0.209932
H=35 K=25 a=0.6 b=0.6 | train_logloss=0.634245 train_brier=0.221796 | test_logloss=0.617414 test_brier=0.213147
H=35 K=25 a=0.6 b=0.8 | train_logloss=0.627372 train_brier=0.218951 | test_logloss=0.602497 test_brier=0.205985
H=35 K=25 a=0.6 b=1 | train_logloss=0.629880 train_brier=0.219776 | test_logloss=0.594151 test_brier=0.201138
H=35 K=25 a=0.7 b=0 | train_logloss=0.634164 train_brier=0.221918 | test_logloss=0.607838 test_brier=0.208708
H=35 K=25 a=0.7 b=0.6 | train_logloss=0.634150 train_brier=0.221822 | test_logloss=0.613683 test_brier=0.211430
H=35 K=25 a=0.7 b=0.8 | train_logloss=0.628090 train_brier=0.219307 | test_logloss=0.601531 test_brier=0.205442
H=35 K=25 a=0.7 b=1 | train_logloss=0.631523 train_brier=0.220385 | test_logloss=0.596303 test_brier=0.201809
H=35 K=25 a=0.75 b=0 | train_logloss=0.634392 train_brier=0.222035 | test_logloss=0.606694 test_brier=0.208185
H=35 K=25 a=0.75 b=0.6 | train_logloss=0.634321 train_brier=0.221936 | test_logloss=0.611937 test_brier=0.210640
H=35 K=25 a=0.75 b=0.8 | train_logloss=0.628719 train_brier=0.219597 | test_logloss=0.601308 test_brier=0.205268
H=35 K=25 a=0.75 b=1 | train_logloss=0.632665 train_brier=0.220801 | test_logloss=0.597766 test_brier=0.202268
H=35 K=25 a=0.85 b=0 | train_logloss=0.635243 train_brier=0.222435 | test_logloss=0.604847 test_brier=0.207333
H=35 K=25 a=0.85 b=0.6 | train_logloss=0.635182 train_brier=0.222398 | test_logloss=0.608879 test_brier=0.209282
H=35 K=25 a=0.85 b=0.8 | train_logloss=0.630598 train_brier=0.220416 | test_logloss=0.601483 test_brier=0.205137
H=35 K=25 a=0.85 b=1 | train_logloss=0.635666 train_brier=0.221864 | test_logloss=0.601534 test_brier=0.203419
H=35 K=30 a=0.5 b=0 | train_logloss=0.633509 train_brier=0.221617 | test_logloss=0.608954 test_brier=0.209124
H=35 K=30 a=0.5 b=0.6 | train_logloss=0.632168 train_brier=0.220880 | test_logloss=0.615817 test_brier=0.212372
H=35 K=30 a=0.5 b=0.8 | train_logloss=0.626745 train_brier=0.218675 | test_logloss=0.599869 test_brier=0.204712
H=35 K=30 a=0.5 b=1 | train_logloss=0.632631 train_brier=0.220706 | test_logloss=0.591971 test_brier=0.199749
H=35 K=30 a=0.6 b=0 | train_logloss=0.633297 train_brier=0.221536 | test_logloss=0.606493 test_brier=0.207979
H=35 K=30 a=0.6 b=0.6 | train_logloss=0.631757 train_brier=0.220750 | test_logloss=0.612453 test_brier=0.210802
H=35 K=30 a=0.6 b=0.8 | train_logloss=0.627036 train_brier=0.218823 | test_logloss=0.599078 test_brier=0.204256
H=35 K=30 a=0.6 b=1 | train_logloss=0.633680 train_brier=0.221051 | test_logloss=0.593761 test_brier=0.200299
H=35 K=30 a=0.7 b=0 | train_logloss=0.633521 train_brier=0.221650 | test_logloss=0.604581 test_brier=0.207085
H=35 K=30 a=0.7 b=0.6 | train_logloss=0.631874 train_brier=0.220868 | test_logloss=0.609414 test_brier=0.209395
H=35 K=30 a=0.7 b=0.8 | train_logloss=0.627984 train_brier=0.219248 | test_logloss=0.598984 test_brier=0.204068
H=35 K=30 a=0.7 b=1 | train_logloss=0.635515 train_brier=0.221676 | test_logloss=0.596628 test_brier=0.201235
H=35 K=30 a=0.75 b=0 | train_logloss=0.633809 train_brier=0.221782 | test_logloss=0.603847 test_brier=0.206734
H=35 K=30 a=0.75 b=0.6 | train_logloss=0.632161 train_brier=0.221031 | test_logloss=0.608047 test_brier=0.208764
H=35 K=30 a=0.75 b=0.8 | train_logloss=0.628737 train_brier=0.219571 | test_logloss=0.599228 test_brier=0.204076
H=35 K=30 a=0.75 b=1 | train_logloss=0.636752 train_brier=0.222093 | test_logloss=0.598488 test_brier=0.201840
H=35 K=30 a=0.85 b=0 | train_logloss=0.634774 train_brier=0.222204 | test_logloss=0.602861 test_brier=0.206231
H=35 K=30 a=0.85 b=0.6 | train_logloss=0.633278 train_brier=0.221590 | test_logloss=0.605761 test_brier=0.207711
H=35 K=30 a=0.85 b=0.8 | train_logloss=0.630869 train_brier=0.220449 | test_logloss=0.600391 test_brier=0.204308
H=35 K=30 a=0.85 b=1 | train_logloss=0.639941 train_brier=0.223144 | test_logloss=0.603110 test_brier=0.203300
H=40 K=10 a=0.5 b=0 | train_logloss=0.646198 train_brier=0.227137 | test_logloss=0.642743 test_brier=0.225282
H=40 K=10 a=0.5 b=0.6 | train_logloss=0.650657 train_brier=0.229185 | test_logloss=0.652058 test_brier=0.229780
H=40 K=10 a=0.5 b=0.8 | train_logloss=0.638844 train_brier=0.223747 | test_logloss=0.632880 test_brier=0.220482
H=40 K=10 a=0.5 b=1 | train_logloss=0.628468 train_brier=0.219274 | test_logloss=0.613536 test_brier=0.211208
H=40 K=10 a=0.6 b=0 | train_logloss=0.645375 train_brier=0.226779 | test_logloss=0.637582 test_brier=0.222824
H=40 K=10 a=0.6 b=0.6 | train_logloss=0.649611 train_brier=0.228708 | test_logloss=0.647132 test_brier=0.227402
H=40 K=10 a=0.6 b=0.8 | train_logloss=0.637943 train_brier=0.223377 | test_logloss=0.628264 test_brier=0.218293
H=40 K=10 a=0.6 b=1 | train_logloss=0.628174 train_brier=0.219205 | test_logloss=0.610867 test_brier=0.209914
H=40 K=10 a=0.7 b=0 | train_logloss=0.644904 train_brier=0.226600 | test_logloss=0.632440 test_brier=0.220415
H=40 K=10 a=0.7 b=0.6 | train_logloss=0.648838 train_brier=0.228373 | test_logloss=0.642081 test_brier=0.224997
H=40 K=10 a=0.7 b=0.8 | train_logloss=0.637477 train_brier=0.223225 | test_logloss=0.623738 test_brier=0.216186
H=40 K=10 a=0.7 b=1 | train_logloss=0.628510 train_brier=0.219427 | test_logloss=0.608620 test_brier=0.208807
H=40 K=10 a=0.75 b=0 | train_logloss=0.644826 train_brier=0.226588 | test_logloss=0.629940 test_brier=0.219265
H=40 K=10 a=0.75 b=0.6 | train_logloss=0.648583 train_brier=0.228272 | test_logloss=0.639578 test_brier=0.223825
H=40 K=10 a=0.75 b=0.8 | train_logloss=0.637444 train_brier=0.223247 | test_logloss=0.621579 test_brier=0.215202
H=40 K=10 a=0.75 b=1 | train_logloss=0.628951 train_brier=0.219659 | test_logloss=0.607705 test_brier=0.208344
H=40 K=10 a=0.85 b=0 | train_logloss=0.645046 train_brier=0.226746 | test_logloss=0.625259 test_brier=0.217170
H=40 K=10 a=0.85 b=0.6 | train_logloss=0.648400 train_brier=0.228237 | test_logloss=0.634882 test_brier=0.221684
H=40 K=10 a=0.85 b=0.8 | train_logloss=0.637868 train_brier=0.223523 | test_logloss=0.617729 test_brier=0.213506
H=40 K=10 a=0.85 b=1 | train_logloss=0.630478 train_brier=0.220391 | test_logloss=0.606486 test_brier=0.207671
H=40 K=15 a=0.5 b=0 | train_logloss=0.639368 train_brier=0.224060 | test_logloss=0.629958 test_brier=0.219140
H=40 K=15 a=0.5 b=0.6 | train_logloss=0.642957 train_brier=0.225614 | test_logloss=0.639263 test_brier=0.223567
H=40 K=15 a=0.5 b=0.8 | train_logloss=0.631812 train_brier=0.220685 | test_logloss=0.619778 test_brier=0.214213
H=40 K=15 a=0.5 b=1 | train_logloss=0.625118 train_brier=0.217954 | test_logloss=0.602761 test_brier=0.205980
H=40 K=15 a=0.6 b=0 | train_logloss=0.638704 train_brier=0.223791 | test_logloss=0.625271 test_brier=0.216940
H=40 K=15 a=0.6 b=0.6 | train_logloss=0.642010 train_brier=0.225208 | test_logloss=0.634314 test_brier=0.221210
H=40 K=15 a=0.6 b=0.8 | train_logloss=0.631279 train_brier=0.220502 | test_logloss=0.616187 test_brier=0.212512
H=40 K=15 a=0.6 b=1 | train_logloss=0.625377 train_brier=0.218103 | test_logloss=0.601783 test_brier=0.205406
H=40 K=15 a=0.7 b=0 | train_logloss=0.638447 train_brier=0.223720 | test_logloss=0.620769 test_brier=0.214863
H=40 K=15 a=0.7 b=0.6 | train_logloss=0.641439 train_brier=0.224993 | test_logloss=0.629343 test_brier=0.218883
H=40 K=15 a=0.7 b=0.8 | train_logloss=0.631290 train_brier=0.220579 | test_logloss=0.612878 test_brier=0.210959
H=40 K=15 a=0.7 b=1 | train_logloss=0.626346 train_brier=0.218556 | test_logloss=0.601465 test_brier=0.205079
H=40 K=15 a=0.75 b=0 | train_logloss=0.638493 train_brier=0.223768 | test_logloss=0.618632 test_brier=0.213893
H=40 K=15 a=0.75 b=0.6 | train_logloss=0.641326 train_brier=0.224972 | test_logloss=0.626926 test_brier=0.217774
H=40 K=15 a=0.75 b=0.8 | train_logloss=0.631534 train_brier=0.220727 | test_logloss=0.611379 test_brier=0.210261
H=40 K=15 a=0.75 b=1 | train_logloss=0.627134 train_brier=0.218904 | test_logloss=0.601586 test_brier=0.205013
H=40 K=15 a=0.85 b=0 | train_logloss=0.638987 train_brier=0.224049 | test_logloss=0.614706 test_brier=0.212151
H=40 K=15 a=0.85 b=0.6 | train_logloss=0.641533 train_brier=0.225139 | test_logloss=0.622466 test_brier=0.215792
H=40 K=15 a=0.85 b=0.8 | train_logloss=0.632589 train_brier=0.221272 | test_logloss=0.608885 test_brier=0.209107
H=40 K=15 a=0.85 b=1 | train_logloss=0.629398 train_brier=0.219857 | test_logloss=0.602507 test_brier=0.205097
H=40 K=20 a=0.5 b=0 | train_logloss=0.635426 train_brier=0.222357 | test_logloss=0.621260 test_brier=0.214989
H=40 K=20 a=0.5 b=0.6 | train_logloss=0.637599 train_brier=0.223208 | test_logloss=0.629902 test_brier=0.219066
H=40 K=20 a=0.5 b=0.8 | train_logloss=0.628034 train_brier=0.219123 | test_logloss=0.611214 test_brier=0.210124
H=40 K=20 a=0.5 b=1 | train_logloss=0.625435 train_brier=0.218090 | test_logloss=0.596961 test_brier=0.202957
H=40 K=20 a=0.6 b=0 | train_logloss=0.634934 train_brier=0.222168 | test_logloss=0.617340 test_brier=0.213160
H=40 K=20 a=0.6 b=0.6 | train_logloss=0.636819 train_brier=0.222896 | test_logloss=0.625328 test_brier=0.216905
H=40 K=20 a=0.6 b=0.8 | train_logloss=0.627833 train_brier=0.219088 | test_logloss=0.608673 test_brier=0.208893
H=40 K=20 a=0.6 b=1 | train_logloss=0.626055 train_brier=0.218351 | test_logloss=0.597206 test_brier=0.202887
H=40 K=20 a=0.7 b=0 | train_logloss=0.634869 train_brier=0.222180 | test_logloss=0.613752 test_brier=0.211508
H=40 K=20 a=0.7 b=0.6 | train_logloss=0.636485 train_brier=0.222805 | test_logloss=0.620871 test_brier=0.214835
H=40 K=20 a=0.7 b=0.8 | train_logloss=0.628238 train_brier=0.219329 | test_logloss=0.606582 test_brier=0.207858
H=40 K=20 a=0.7 b=1 | train_logloss=0.627415 train_brier=0.218907 | test_logloss=0.598282 test_brier=0.203116
H=40 K=20 a=0.75 b=0 | train_logloss=0.635016 train_brier=0.222269 | test_logloss=0.612114 test_brier=0.210761
H=40 K=20 a=0.75 b=0.6 | train_logloss=0.636522 train_brier=0.222858 | test_logloss=0.618743 test_brier=0.213865
H=40 K=20 a=0.75 b=0.8 | train_logloss=0.628698 train_brier=0.219561 | test_logloss=0.605760 test_brier=0.207434
H=40 K=20 a=0.75 b=1 | train_logloss=0.628411 train_brier=0.219303 | test_logloss=0.599159 test_brier=0.203339
H=40 K=20 a=0.85 b=0 | train_logloss=0.635712 train_brier=0.222622 | test_logloss=0.609233 test_brier=0.209460
H=40 K=20 a=0.85 b=0.6 | train_logloss=0.637078 train_brier=0.223188 | test_logloss=0.614903 test_brier=0.212165
H=40 K=20 a=0.85 b=0.8 | train_logloss=0.630223 train_brier=0.220274 | test_logloss=0.604626 test_brier=0.206788
H=40 K=20 a=0.85 b=1 | train_logloss=0.631110 train_brier=0.220338 | test_logloss=0.601690 test_brier=0.204009
H=40 K=25 a=0.5 b=0 | train_logloss=0.633297 train_brier=0.221475 | test_logloss=0.614983 test_brier=0.211982
H=40 K=25 a=0.5 b=0.6 | train_logloss=0.633822 train_brier=0.221564 | test_logloss=0.622760 test_brier=0.215655
H=40 K=25 a=0.5 b=0.8 | train_logloss=0.626185 train_brier=0.218396 | test_logloss=0.605272 test_brier=0.207253
H=40 K=25 a=0.5 b=1 | train_logloss=0.627730 train_brier=0.218922 | test_logloss=0.594001 test_brier=0.201106
H=40 K=25 a=0.6 b=0 | train_logloss=0.632955 train_brier=0.221346 | test_logloss=0.611824 test_brier=0.210505
H=40 K=25 a=0.6 b=0.6 | train_logloss=0.633227 train_brier=0.221345 | test_logloss=0.618727 test_brier=0.213755
H=40 K=25 a=0.6 b=0.8 | train_logloss=0.626259 train_brier=0.218469 | test_logloss=0.603658 test_brier=0.206424
H=40 K=25 a=0.6 b=1 | train_logloss=0.628595 train_brier=0.219240 | test_logloss=0.595096 test_brier=0.201376
H=40 K=25 a=0.7 b=0 | train_logloss=0.633047 train_brier=0.221417 | test_logloss=0.609120 test_brier=0.209246
H=40 K=25 a=0.7 b=0.6 | train_logloss=0.633126 train_brier=0.221366 | test_logloss=0.614943 test_brier=0.211996
H=40 K=25 a=0.7 b=0.8 | train_logloss=0.626968 train_brier=0.218819 | test_logloss=0.602628 test_brier=0.205828
H=40 K=25 a=0.7 b=1 | train_logloss=0.630221 train_brier=0.219844 | test_logloss=0.597178 test_brier=0.201999
H=40 K=25 a=0.75 b=0 | train_logloss=0.633272 train_brier=0.221531 | test_logloss=0.607960 test_brier=0.208705
H=40 K=25 a=0.75 b=0.6 | train_logloss=0.633293 train_brier=0.221477 | test_logloss=0.613181 test_brier=0.211187
H=40 K=25 a=0.75 b=0.8 | train_logloss=0.627592 train_brier=0.219106 | test_logloss=0.602362 test_brier=0.205622
H=40 K=25 a=0.75 b=1 | train_logloss=0.631352 train_brier=0.220257 | test_logloss=0.598605 test_brier=0.202434
H=40 K=25 a=0.85 b=0 | train_logloss=0.634119 train_brier=0.221927 | test_logloss=0.606080 test_brier=0.207814
H=40 K=25 a=0.85 b=0.6 | train_logloss=0.634141 train_brier=0.221930 | test_logloss=0.610071 test_brier=0.209784
H=40 K=25 a=0.85 b=0.8 | train_logloss=0.629459 train_brier=0.219919 | test_logloss=0.602453 test_brier=0.205427

,train_start,train_end,test_year,best_H,best_K,best_a,best_b,train_logloss,test_logloss,train_brier,test_brier
0,2015,2019,2020,35,30,0.5,1.0,0.632631,0.591971,0.220706,0.199749
1,2015,2020,2021,35,30,0.6,0.8,0.623764,0.606534,0.217118,0.210775
2,2015,2021,2022,35,15,0.6,1.0,0.621091,0.610753,0.216107,0.211770
3,2015,2022,2023,35,20,0.5,1.0,0.619576,0.601675,0.215485,0.206994
4,2015,2023,2024,35,30,0.5,0.8,0.617772,0.596690,0.214619,0.203809

In [ ]:
initial_train_years = [2015, 2016, 2017, 2018, 2019]
all_years = list(range(2015, 2025))

H_list = [25, 30, 35, 40]
K_list = [15, 20, 25, 30, 35]
a_list = [0.45, 0.50, 0.55, 0.60, 0.65]
b_list = [0.8, 0.9, 1.0]

# MOV choices:
# - no MOV  -> use_mov=False (b ignored, but we'll include b=0.8 as a placeholder)
# - MOV w/ exponent -> use_mov=True and b in {0.6,0.8,1.0}

train = initial_train_years.copy()
summary_rows = []

while True:
    last_train = train[-1]
    idx = all_years.index(last_train)
    if idx + 1 >= len(all_years):
        break
    test_year = all_years[idx + 1]

    print(f"\n=== WALKFORWARD: train={train[0]}-{train[-1]} test={test_year} ===")

    res = run_gridsearch(
        train_years=train,
        test_years=[test_year],
        H_list=H_list,
        K_list=K_list,
        a_list=a_list,
        b_list=b_list,
        verbose=True,
    )

    best = res.iloc[0].to_dict()
    summary_rows.append({
        "train_start": train[0],
        "train_end": train[-1],
        "test_year": test_year,
        "best_H": best["H"],
        "best_K": best["K"],
        "best_a": best["a"],
        "best_b": best["b"],
        "train_logloss": best["train_logloss"],
        "test_logloss": best["test_logloss"],
        "train_brier": best["train_brier"],
        "test_brier": best["test_brier"],
    })

    train = train + [test_year]

summary = pd.DataFrame(summary_rows)
summary

=== WALKFORWARD: train=2015-2019 test=2020 ===
H=25 K=15 a=0.45 b=0.8 | train_logloss=0.635897 train_brier=0.222496 | test_logloss=0.618147 test_brier=0.213476
H=25 K=15 a=0.45 b=0.9 | train_logloss=0.631629 train_brier=0.220693 | test_logloss=0.608730 test_brier=0.209099
H=25 K=15 a=0.45 b=1 | train_logloss=0.629197 train_brier=0.219708 | test_logloss=0.600398 test_brier=0.205203
H=25 K=15 a=0.5 b=0.8 | train_logloss=0.635468 train_brier=0.222324 | test_logloss=0.616353 test_brier=0.212644
H=25 K=15 a=0.5 b=0.9 | train_logloss=0.631352 train_brier=0.220593 | test_logloss=0.607476 test_brier=0.208519
H=25 K=15 a=0.5 b=1 | train_logloss=0.629102 train_brier=0.219682 | test_logloss=0.599776 test_brier=0.204899
H=25 K=15 a=0.55 b=0.8 | train_logloss=0.635152 train_brier=0.222210 | test_logloss=0.614604 test_brier=0.211839
H=25 K=15 a=0.55 b=0.9 | train_logloss=0.631211 train_brier=0.220558 | test_logloss=0.606318 test_brier=0.207983
H=25 K=15 a=0.55 b=1 | train_logloss=0.629165 train_brier=0.219727 | test_logloss=0.599304 test_brier=0.204657
H=25 K=15 a=0.6 b=0.8 | train_logloss=0.634962 train_brier=0.222157 | test_logloss=0.612910 test_brier=0.211064
H=25 K=15 a=0.6 b=0.9 | train_logloss=0.631216 train_brier=0.220592 | test_logloss=0.605270 test_brier=0.207497
H=25 K=15 a=0.6 b=1 | train_logloss=0.629395 train_brier=0.219846 | test_logloss=0.598988 test_brier=0.204477
H=25 K=15 a=0.65 b=0.8 | train_logloss=0.634908 train_brier=0.222169 | test_logloss=0.611283 test_brier=0.210325
H=25 K=15 a=0.65 b=0.9 | train_logloss=0.631377 train_brier=0.220696 | test_logloss=0.604338 test_brier=0.207060
H=25 K=15 a=0.65 b=1 | train_logloss=0.629804 train_brier=0.220041 | test_logloss=0.598845 test_brier=0.204363
H=25 K=20 a=0.45 b=0.8 | train_logloss=0.632105 train_brier=0.220904 | test_logloss=0.609303 test_brier=0.209373
H=25 K=20 a=0.45 b=0.9 | train_logloss=0.629540 train_brier=0.219860 | test_logloss=0.600939 test_brier=0.205467
H=25 K=20 a=0.45 b=1 | train_logloss=0.629562 train_brier=0.219848 | test_logloss=0.594299 test_brier=0.202206
H=25 K=20 a=0.5 b=0.8 | train_logloss=0.631819 train_brier=0.220799 | test_logloss=0.607969 test_brier=0.208758
H=25 K=20 a=0.5 b=0.9 | train_logloss=0.629426 train_brier=0.219825 | test_logloss=0.600223 test_brier=0.205125
H=25 K=20 a=0.5 b=1 | train_logloss=0.629638 train_brier=0.219878 | test_logloss=0.594226 test_brier=0.202129
H=25 K=20 a=0.55 b=0.8 | train_logloss=0.631663 train_brier=0.220756 | test_logloss=0.606733 test_brier=0.208190
H=25 K=20 a=0.55 b=0.9 | train_logloss=0.629460 train_brier=0.219858 | test_logloss=0.599649 test_brier=0.204843
H=25 K=20 a=0.55 b=1 | train_logloss=0.629879 train_brier=0.219978 | test_logloss=0.594354 test_brier=0.202133
H=25 K=20 a=0.6 b=0.8 | train_logloss=0.631645 train_brier=0.220778 | test_logloss=0.605604 test_brier=0.207670
H=25 K=20 a=0.6 b=0.9 | train_logloss=0.629654 train_brier=0.219960 | test_logloss=0.599233 test_brier=0.204625
H=25 K=20 a=0.6 b=1 | train_logloss=0.630297 train_brier=0.220152 | test_logloss=0.594682 test_brier=0.202213
H=25 K=20 a=0.65 b=0.8 | train_logloss=0.631780 train_brier=0.220869 | test_logloss=0.604585 test_brier=0.207199
H=25 K=20 a=0.65 b=0.9 | train_logloss=0.630017 train_brier=0.220136 | test_logloss=0.598984 test_brier=0.204471
H=25 K=20 a=0.65 b=1 | train_logloss=0.630909 train_brier=0.220402 | test_logloss=0.595225 test_brier=0.202369
H=25 K=25 a=0.45 b=0.8 | train_logloss=0.630269 train_brier=0.220167 | test_logloss=0.603123 test_brier=0.206501
H=25 K=25 a=0.45 b=0.9 | train_logloss=0.629470 train_brier=0.219838 | test_logloss=0.595944 test_brier=0.203050
H=25 K=25 a=0.45 b=1 | train_logloss=0.631966 train_brier=0.220716 | test_logloss=0.591183 test_brier=0.200405
H=25 K=25 a=0.5 b=0.8 | train_logloss=0.630101 train_brier=0.220110 | test_logloss=0.602196 test_brier=0.206069
H=25 K=25 a=0.5 b=0.9 | train_logloss=0.629480 train_brier=0.219844 | test_logloss=0.595648 test_brier=0.202885
H=25 K=25 a=0.5 b=1 | train_logloss=0.632155 train_brier=0.220773 | test_logloss=0.591480 test_brier=0.200469
H=25 K=25 a=0.55 b=0.8 | train_logloss=0.630074 train_brier=0.220117 | test_logloss=0.601402 test_brier=0.205695
H=25 K=25 a=0.55 b=0.9 | train_logloss=0.629649 train_brier=0.219920 | test_logloss=0.595534 test_brier=0.202794
H=25 K=25 a=0.55 b=1 | train_logloss=0.632519 train_brier=0.220901 | test_logloss=0.592015 test_brier=0.200630
H=25 K=25 a=0.6 b=0.8 | train_logloss=0.630198 train_brier=0.220193 | test_logloss=0.600749 test_brier=0.205381
H=25 K=25 a=0.6 b=0.9 | train_logloss=0.629982 train_brier=0.220065 | test_logloss=0.595605 test_brier=0.202775
H=25 K=25 a=0.6 b=1 | train_logloss=0.633065 train_brier=0.221101 | test_logloss=0.592787 test_brier=0.200879
H=25 K=25 a=0.65 b=0.8 | train_logloss=0.630479 train_brier=0.220338 | test_logloss=0.600253 test_brier=0.205130
H=25 K=25 a=0.65 b=0.9 | train_logloss=0.630491 train_brier=0.220282 | test_logloss=0.595879 test_brier=0.202831
H=25 K=25 a=0.65 b=1 | train_logloss=0.633806 train_brier=0.221373 | test_logloss=0.593804 test_brier=0.201216
H=25 K=30 a=0.45 b=0.8 | train_logloss=0.629702 train_brier=0.219951 | test_logloss=0.598672 test_brier=0.204392
H=25 K=30 a=0.45 b=0.9 | train_logloss=0.630676 train_brier=0.220287 | test_logloss=0.592797 test_brier=0.201389
H=25 K=30 a=0.45 b=1 | train_logloss=0.635684 train_brier=0.222001 | test_logloss=0.590036 test_brier=0.199342
H=25 K=30 a=0.5 b=0.8 | train_logloss=0.629631 train_brier=0.219928 | test_logloss=0.598091 test_brier=0.204109
H=25 K=30 a=0.5 b=0.9 | train_logloss=0.630780 train_brier=0.220319 | test_logloss=0.592808 test_brier=0.201345
H=25 K=30 a=0.5 b=1 | train_logloss=0.635955 train_brier=0.222073 | test_logloss=0.590602 test_brier=0.199498
H=25 K=30 a=0.55 b=0.8 | train_logloss=0.629706 train_brier=0.219971 | test_logloss=0.597664 test_brier=0.203892
H=25 K=30 a=0.55 b=0.9 | train_logloss=0.631044 train_brier=0.220420 | test_logloss=0.593042 test_brier=0.201391
H=25 K=30 a=0.55 b=1 | train_logloss=0.636404 train_brier=0.222213 | test_logloss=0.591419 test_brier=0.199756
H=25 K=30 a=0.6 b=0.8 | train_logloss=0.629937 train_brier=0.220082 | test_logloss=0.597407 test_brier=0.203743
H=25 K=30 a=0.6 b=0.9 | train_logloss=0.631480 train_brier=0.220589 | test_logloss=0.593493 test_brier=0.201521
H=25 K=30 a=0.6 b=1 | train_logloss=0.637038 train_brier=0.222422 | test_logloss=0.592507 test_brier=0.200119
H=25 K=30 a=0.65 b=0.8 | train_logloss=0.630334 train_brier=0.220262 | test_logloss=0.597329 test_brier=0.203662
H=25 K=30 a=0.65 b=0.9 | train_logloss=0.632100 train_brier=0.220830 | test_logloss=0.594167 test_brier=0.201732
H=25 K=30 a=0.65 b=1 | train_logloss=0.637869 train_brier=0.222700 | test_logloss=0.593865 test_brier=0.200578
H=25 K=35 a=0.45 b=0.8 | train_logloss=0.630005 train_brier=0.220071 | test_logloss=0.595460 test_brier=0.202804
H=25 K=35 a=0.45 b=0.9 | train_logloss=0.632768 train_brier=0.221037 | test_logloss=0.590971 test_brier=0.200239
H=25 K=35 a=0.45 b=1 | train_logloss=0.640321 train_brier=0.223541 | test_logloss=0.590301 test_brier=0.198789
H=25 K=35 a=0.5 b=0.8 | train_logloss=0.630015 train_brier=0.220074 | test_logloss=0.595147 test_brier=0.202633
H=25 K=35 a=0.5 b=0.9 | train_logloss=0.632938 train_brier=0.221083 | test_logloss=0.591228 test_brier=0.200286
H=25 K=35 a=0.5 b=1 | train_logloss=0.640653 train_brier=0.223619 | test_logloss=0.591081 test_brier=0.199011
H=25 K=35 a=0.55 b=0.8 | train_logloss=0.630177 train_brier=0.220144 | test_logloss=0.595028 test_brier=0.202542
H=25 K=35 a=0.55 b=0.9 | train_logloss=0.633277 train_brier=0.221198 | test_logloss=0.591714 test_brier=0.200426
H=25 K=35 a=0.55 b=1 | train_logloss=0.641162 train_brier=0.223762 | test_logloss=0.592117 test_brier=0.199332
H=25 K=35 a=0.6 b=0.8 | train_logloss=0.630496 train_brier=0.220279 | test_logloss=0.595098 test_brier=0.202526
H=25 K=35 a=0.6 b=0.9 | train_logloss=0.633791 train_brier=0.221380 | test_logloss=0.592448 test_brier=0.200662
H=25 K=35 a=0.6 b=1 | train_logloss=0.641863 train_brier=0.223973 | test_logloss=0.593423 test_brier=0.199757
H=25 K=35 a=0.65 b=0.8 | train_logloss=0.630982 train_brier=0.220481 | test_logloss=0.595368 test_brier=0.202584
H=25 K=35 a=0.65 b=0.9 | train_logloss=0.634487 train_brier=0.221630 | test_logloss=0.593426 test_brier=0.200986
H=25 K=35 a=0.65 b=1 | train_logloss=0.642765 train_brier=0.224250 | test_logloss=0.595033 test_brier=0.200298
H=30 K=15 a=0.45 b=0.8 | train_logloss=0.634478 train_brier=0.221849 | test_logloss=0.619113 test_brier=0.213916
H=30 K=15 a=0.45 b=0.9 | train_logloss=0.630164 train_brier=0.220038 | test_logloss=0.609638 test_brier=0.209473
H=30 K=15 a=0.45 b=1 | train_logloss=0.627673 train_brier=0.219042 | test_logloss=0.601233 test_brier=0.205496
H=30 K=15 a=0.5 b=0.8 | train_logloss=0.634045 train_brier=0.221676 | test_logloss=0.617298 test_brier=0.213067
H=30 K=15 a=0.5 b=0.9 | train_logloss=0.629885 train_brier=0.219937 | test_logloss=0.608359 test_brier=0.208872
H=30 K=15 a=0.5 b=1 | train_logloss=0.627575 train_brier=0.219014 | test_logloss=0.600584 test_brier=0.205170
H=30 K=15 a=0.55 b=0.8 | train_logloss=0.633726 train_brier=0.221561 | test_logloss=0.615522 test_brier=0.212241
H=30 K=15 a=0.55 b=0.9 | train_logloss=0.629739 train_brier=0.219900 | test_logloss=0.607177 test_brier=0.208315
H=30 K=15 a=0.55 b=1 | train_logloss=0.627632 train_brier=0.219058 | test_logloss=0.600085 test_brier=0.204905
H=30 K=15 a=0.6 b=0.8 | train_logloss=0.633531 train_brier=0.221505 | test_logloss=0.613806 test_brier=0.211447
H=30 K=15 a=0.6 b=0.9 | train_logloss=0.629738 train_brier=0.219931 | test_logloss=0.606098 test_brier=0.207805
H=30 K=15 a=0.6 b=1 | train_logloss=0.627856 train_brier=0.219174 | test_logloss=0.599744 test_brier=0.204704
H=30 K=15 a=0.65 b=0.8 | train_logloss=0.633472 train_brier=0.221515 | test_logloss=0.612158 test_brier=0.210691
H=30 K=15 a=0.65 b=0.9 | train_logloss=0.629895 train_brier=0.220034 | test_logloss=0.605137 test_brier=0.207345
H=30 K=15 a=0.65 b=1 | train_logloss=0.628259 train_brier=0.219368 | test_logloss=0.599567 test_brier=0.204565
H=30 K=20 a=0.45 b=0.8 | train_logloss=0.630641 train_brier=0.220247 | test_logloss=0.610214 test_brier=0.209751
H=30 K=20 a=0.45 b=0.9 | train_logloss=0.628021 train_brier=0.219194 | test_logloss=0.601784 test_brier=0.205769
H=30 K=20 a=0.45 b=1 | train_logloss=0.627966 train_brier=0.219165 | test_logloss=0.595056 test_brier=0.202419
H=30 K=20 a=0.5 b=0.8 | train_logloss=0.630352 train_brier=0.220141 | test_logloss=0.608859 test_brier=0.209118
H=30 K=20 a=0.5 b=0.9 | train_logloss=0.627902 train_brier=0.219157 | test_logloss=0.601041 test_brier=0.205405
H=30 K=20 a=0.5 b=1 | train_logloss=0.628038 train_brier=0.219194 | test_logloss=0.594947 test_brier=0.202317
H=30 K=20 a=0.55 b=0.8 | train_logloss=0.630194 train_brier=0.220097 | test_logloss=0.607595 test_brier=0.208527
H=30 K=20 a=0.55 b=0.9 | train_logloss=0.627933 train_brier=0.219188 | test_logloss=0.600443 test_brier=0.205102
H=30 K=20 a=0.55 b=1 | train_logloss=0.628272 train_brier=0.219293 | test_logloss=0.595035 test_brier=0.202295
H=30 K=20 a=0.6 b=0.8 | train_logloss=0.630173 train_brier=0.220119 | test_logloss=0.606434 test_brier=0.207983
H=30 K=20 a=0.6 b=0.9 | train_logloss=0.628122 train_brier=0.219290 | test_logloss=0.599998 test_brier=0.204861
H=30 K=20 a=0.6 b=1 | train_logloss=0.628682 train_brier=0.219465 | test_logloss=0.595329 test_brier=0.202351
H=30 K=20 a=0.65 b=0.8 | train_logloss=0.630302 train_brier=0.220208 | test_logloss=0.605392 test_brier=0.207492
H=30 K=20 a=0.65 b=0.9 | train_logloss=0.628481 train_brier=0.219465 | test_logloss=0.599717 test_brier=0.204683
H=30 K=20 a=0.65 b=1 | train_logloss=0.629276 train_brier=0.219709 | test_logloss=0.595840 test_brier=0.202485
H=30 K=25 a=0.45 b=0.8 | train_logloss=0.628768 train_brier=0.219504 | test_logloss=0.603979 test_brier=0.206822
H=30 K=25 a=0.45 b=0.9 | train_logloss=0.627904 train_brier=0.219162 | test_logloss=0.596739 test_brier=0.203295
H=30 K=25 a=0.45 b=1 | train_logloss=0.630292 train_brier=0.220013 | test_logloss=0.591866 test_brier=0.200556
H=30 K=25 a=0.5 b=0.8 | train_logloss=0.628600 train_brier=0.219447 | test_logloss=0.603030 test_brier=0.206370
H=30 K=25 a=0.5 b=0.9 | train_logloss=0.627910 train_brier=0.219168 | test_logloss=0.596410 test_brier=0.203106
H=30 K=25 a=0.5 b=1 | train_logloss=0.630476 train_brier=0.220071 | test_logloss=0.592137 test_brier=0.200603
H=30 K=25 a=0.55 b=0.8 | train_logloss=0.628569 train_brier=0.219453 | test_logloss=0.602209 test_brier=0.205975
H=30 K=25 a=0.55 b=0.9 | train_logloss=0.628068 train_brier=0.219240 | test_logloss=0.596266 test_brier=0.202992
H=30 K=25 a=0.55 b=1 | train_logloss=0.630832 train_brier=0.220198 | test_logloss=0.592641 test_brier=0.200743
H=30 K=25 a=0.6 b=0.8 | train_logloss=0.628687 train_brier=0.219527 | test_logloss=0.601528 test_brier=0.205638
H=30 K=25 a=0.6 b=0.9 | train_logloss=0.628391 train_brier=0.219382 | test_logloss=0.596309 test_brier=0.202951
H=30 K=25 a=0.6 b=1 | train_logloss=0.631370 train_brier=0.220396 | test_logloss=0.593383 test_brier=0.200973
H=30 K=25 a=0.65 b=0.8 | train_logloss=0.628965 train_brier=0.219671 | test_logloss=0.600995 test_brier=0.205360
H=30 K=25 a=0.65 b=0.9 | train_logloss=0.628892 train_brier=0.219597 | test_logloss=0.596545 test_brier=0.202981
H=30 K=25 a=0.65 b=1 | train_logloss=0.632098 train_brier=0.220666 | test_logloss=0.594371 test_brier=0.201290
H=30 K=30 a=0.45 b=0.8 | train_logloss=0.628162 train_brier=0.219279 | test_logloss=0.599505 test_brier=0.204674
H=30 K=30 a=0.45 b=0.9 | train_logloss=0.629054 train_brier=0.219597 | test_logloss=0.593535 test_brier=0.201583
H=30 K=30 a=0.45 b=1 | train_logloss=0.633924 train_brier=0.221276 | test_logloss=0.590641 test_brier=0.199437
H=30 K=30 a=0.5 b=0.8 | train_logloss=0.628089 train_brier=0.219256 | test_logloss=0.598890 test_brier=0.204367
H=30 K=30 a=0.5 b=0.9 | train_logloss=0.629152 train_brier=0.219629 | test_logloss=0.593523 test_brier=0.201521
H=30 K=30 a=0.5 b=1 | train_logloss=0.634188 train_brier=0.221348 | test_logloss=0.591191 test_brier=0.199584
H=30 K=30 a=0.55 b=0.8 | train_logloss=0.628160 train_brier=0.219298 | test_logloss=0.598442 test_brier=0.204131
H=30 K=30 a=0.55 b=0.9 | train_logloss=0.629408 train_brier=0.219727 | test_logloss=0.593724 test_brier=0.201546
H=30 K=30 a=0.55 b=1 | train_logloss=0.634626 train_brier=0.221487 | test_logloss=0.591985 test_brier=0.199827
H=30 K=30 a=0.6 b=0.8 | train_logloss=0.628386 train_brier=0.219407 | test_logloss=0.598158 test_brier=0.203960
H=30 K=30 a=0.6 b=0.9 | train_logloss=0.629836 train_brier=0.219895 | test_logloss=0.594147 test_brier=0.201656
H=30 K=30 a=0.6 b=1 | train_logloss=0.635252 train_brier=0.221695 | test_logloss=0.593036 test_brier=0.200168
H=30 K=30 a=0.65 b=0.8 | train_logloss=0.628775 train_brier=0.219585 | test_logloss=0.598048 test_brier=0.203856
H=30 K=30 a=0.65 b=0.9 | train_logloss=0.630445 train_brier=0.220133 | test_logloss=0.594788 test_brier=0.201845
H=30 K=30 a=0.65 b=1 | train_logloss=0.636074 train_brier=0.221973 | test_logloss=0.594365 test_brier=0.200610
H=30 K=35 a=0.45 b=0.8 | train_logloss=0.628430 train_brier=0.219392 | test_logloss=0.596258 test_brier=0.203049
H=30 K=35 a=0.45 b=0.9 | train_logloss=0.631087 train_brier=0.220331 | test_logloss=0.591648 test_brier=0.200387
H=30 K=35 a=0.45 b=1 | train_logloss=0.638473 train_brier=0.222794 | test_logloss=0.590827 test_brier=0.198833
H=30 K=35 a=0.5 b=0.8 | train_logloss=0.628436 train_brier=0.219394 | test_logloss=0.595922 test_brier=0.202858
H=30 K=35 a=0.5 b=0.9 | train_logloss=0.631253 train_brier=0.220378 | test_logloss=0.591887 test_brier=0.200421
H=30 K=35 a=0.5 b=1 | train_logloss=0.638800 train_brier=0.222873 | test_logloss=0.591589 test_brier=0.199045
H=30 K=35 a=0.55 b=0.8 | train_logloss=0.628589 train_brier=0.219461 | test_logloss=0.595774 test_brier=0.202746
H=30 K=35 a=0.55 b=0.9 | train_logloss=0.631584 train_brier=0.220492 | test_logloss=0.592345 test_brier=0.200541
H=30 K=35 a=0.55 b=1 | train_logloss=0.639307 train_brier=0.223019 | test_logloss=0.592606 test_brier=0.199358
H=30 K=35 a=0.6 b=0.8 | train_logloss=0.628899 train_brier=0.219593 | test_logloss=0.595815 test_brier=0.202707
H=30 K=35 a=0.6 b=0.9 | train_logloss=0.632088 train_brier=0.220673 | test_logloss=0.593046 test_brier=0.200757
H=30 K=35 a=0.6 b=1 | train_logloss=0.640000 train_brier=0.223230 | test_logloss=0.593896 test_brier=0.199777
H=30 K=35 a=0.65 b=0.8 | train_logloss=0.629379 train_brier=0.219795 | test_logloss=0.596051 test_brier=0.202742
H=30 K=35 a=0.65 b=0.9 | train_logloss=0.632775 train_brier=0.220922 | test_logloss=0.593997 test_brier=0.201063
H=30 K=35 a=0.65 b=1 | train_logloss=0.640890 train_brier=0.223506 | test_logloss=0.595468 test_brier=0.200296
H=35 K=15 a=0.45 b=0.8 | train_logloss=0.633265 train_brier=0.221306 | test_logloss=0.620273 test_brier=0.214456
H=35 K=15 a=0.45 b=0.9 | train_logloss=0.628904 train_brier=0.219481 | test_logloss=0.610738 test_brier=0.209942
H=35 K=15 a=0.45 b=1 | train_logloss=0.626348 train_brier=0.218467 | test_logloss=0.602261 test_brier=0.205882
H=35 K=15 a=0.5 b=0.8 | train_logloss=0.632828 train_brier=0.221131 | test_logloss=0.618435 test_brier=0.213588
H=35 K=15 a=0.5 b=0.9 | train_logloss=0.628618 train_brier=0.219377 | test_logloss=0.609434 test_brier=0.209320
H=35 K=15 a=0.5 b=1 | train_logloss=0.626246 train_brier=0.218438 | test_logloss=0.601583 test_brier=0.205532
H=35 K=15 a=0.55 b=0.8 | train_logloss=0.632504 train_brier=0.221012 | test_logloss=0.616636 test_brier=0.212743
H=35 K=15 a=0.55 b=0.9 | train_logloss=0.628468 train_brier=0.219338 | test_logloss=0.608220 test_brier=0.208739
H=35 K=15 a=0.55 b=1 | train_logloss=0.626298 train_brier=0.218479 | test_logloss=0.601053 test_brier=0.205243
H=35 K=15 a=0.6 b=0.8 | train_logloss=0.632305 train_brier=0.220954 | test_logloss=0.614893 test_brier=0.211929
H=35 K=15 a=0.6 b=0.9 | train_logloss=0.628461 train_brier=0.219366 | test_logloss=0.607109 test_brier=0.208203
H=35 K=15 a=0.6 b=1 | train_logloss=0.626515 train_brier=0.218593 | test_logloss=0.600682 test_brier=0.205017
H=35 K=15 a=0.65 b=0.8 | train_logloss=0.632240 train_brier=0.220961 | test_logloss=0.613226 test_brier=0.211154
H=35 K=15 a=0.65 b=0.9 | train_logloss=0.628612 train_brier=0.219466 | test_logloss=0.606116 test_brier=0.207718
H=35 K=15 a=0.65 b=1 | train_logloss=0.626911 train_brier=0.218783 | test_logloss=0.600477 test_brier=0.204853
H=35 K=20 a=0.45 b=0.8 | train_logloss=0.629382 train_brier=0.219690 | test_logloss=0.611323 test_brier=0.210229
H=35 K=20 a=0.45 b=0.9 | train_logloss=0.626702 train_brier=0.218620 | test_logloss=0.602814 test_brier=0.206161
H=35 K=20 a=0.45 b=1 | train_logloss=0.626570 train_brier=0.218571 | test_logloss=0.595999 test_brier=0.202718
H=35 K=20 a=0.5 b=0.8 | train_logloss=0.629088 train_brier=0.219582 | test_logloss=0.609943 test_brier=0.209574
H=35 K=20 a=0.5 b=0.9 | train_logloss=0.626581 train_brier=0.218582 | test_logloss=0.602037 test_brier=0.205771
H=35 K=20 a=0.5 b=1 | train_logloss=0.626637 train_brier=0.218599 | test_logloss=0.595853 test_brier=0.202591
H=35 K=20 a=0.55 b=0.8 | train_logloss=0.628926 train_brier=0.219536 | test_logloss=0.608652 test_brier=0.208961
H=35 K=20 a=0.55 b=0.9 | train_logloss=0.626606 train_brier=0.218612 | test_logloss=0.601411 test_brier=0.205445
H=35 K=20 a=0.55 b=1 | train_logloss=0.626867 train_brier=0.218697 | test_logloss=0.595915 test_brier=0.202547
H=35 K=20 a=0.6 b=0.8 | train_logloss=0.628901 train_brier=0.219555 | test_logloss=0.607462 test_brier=0.208394
H=35 K=20 a=0.6 b=0.9 | train_logloss=0.626789 train_brier=0.218710 | test_logloss=0.600936 test_brier=0.205179
H=35 K=20 a=0.6 b=1 | train_logloss=0.627269 train_brier=0.218865 | test_logloss=0.596175 test_brier=0.202578
H=35 K=20 a=0.65 b=0.8 | train_logloss=0.629027 train_brier=0.219642 | test_logloss=0.606384 test_brier=0.207875

,train_start,train_end,test_year,best_H,best_K,best_a,best_b,train_logloss,test_logloss,train_brier,test_brier
0,2015,2019,2020,25,30,0.45,1.0,0.635684,0.590036,0.222001,0.199342
1,2015,2020,2021,30,25,0.50,0.9,0.624223,0.606307,0.217288,0.210808
2,2015,2021,2022,30,15,0.55,1.0,0.621856,0.610734,0.216431,0.211762
3,2015,2022,2023,25,20,0.45,1.0,0.621385,0.600106,0.216292,0.206366
4,2015,2023,2024,35,35,0.45,0.8,0.617760,0.595180,0.214626,0.202870

In [7]:
initial_train_years = [2015, 2016, 2017, 2018, 2019]
all_years = list(range(2015, 2025))

H_list = [25, 30, 35, 40]
K_list = [15, 20, 25, 30, 35]
a_list = [0.45, 0.50, 0.55, 0.60, 0.65]
b_list = [0.8, 0.9, 1.0]

# MOV choices:
# - no MOV  -> use_mov=False (b ignored, but we'll include b=0.8 as a placeholder)
# - MOV w/ exponent -> use_mov=True and b in {0.6,0.8,1.0}

all_step_results = []   # stores full res df for each test_year
summary_rows = []

train = initial_train_years.copy()

while True:
    last_train = train[-1]
    idx = all_years.index(last_train)
    if idx + 1 >= len(all_years):
        break
    test_year = all_years[idx + 1]

    print(f"\n=== WALKFORWARD: train={train[0]}-{train[-1]} test={test_year} ===")

    res = run_gridsearch(
        train_years=train,
        test_years=[test_year],
        H_list=H_list,
        K_list=K_list,
        a_list=a_list,
        b_list=b_list,
        verbose=True,
    )

    # tag which held-out year this result corresponds to
    res = res.copy()
    res["heldout_year"] = test_year
    all_step_results.append(res)

    best = res.iloc[0].to_dict()
    summary_rows.append({
        "train_start": train[0],
        "train_end": train[-1],
        "test_year": test_year,
        "best_H": best["H"],
        "best_K": best["K"],
        "best_a": best["a"],
        "best_b": best["b"],
        "train_logloss": best["train_logloss"],
        "test_logloss": best["test_logloss"],
        "train_brier": best["train_brier"],
        "test_brier": best["test_brier"],
    })

    train = train + [test_year]

summary = pd.DataFrame(summary_rows)
summary

=== WALKFORWARD: train=2015-2019 test=2020 ===
H=25 K=15 a=0.45 b=0.8 | train_logloss=0.635897 train_brier=0.222496 | test_logloss=0.618147 test_brier=0.213476
H=25 K=15 a=0.45 b=0.9 | train_logloss=0.631629 train_brier=0.220693 | test_logloss=0.608730 test_brier=0.209099
H=25 K=15 a=0.45 b=1 | train_logloss=0.629197 train_brier=0.219708 | test_logloss=0.600398 test_brier=0.205203
H=25 K=15 a=0.5 b=0.8 | train_logloss=0.635468 train_brier=0.222324 | test_logloss=0.616353 test_brier=0.212644
H=25 K=15 a=0.5 b=0.9 | train_logloss=0.631352 train_brier=0.220593 | test_logloss=0.607476 test_brier=0.208519
H=25 K=15 a=0.5 b=1 | train_logloss=0.629102 train_brier=0.219682 | test_logloss=0.599776 test_brier=0.204899
H=25 K=15 a=0.55 b=0.8 | train_logloss=0.635152 train_brier=0.222210 | test_logloss=0.614604 test_brier=0.211839
H=25 K=15 a=0.55 b=0.9 | train_logloss=0.631211 train_brier=0.220558 | test_logloss=0.606318 test_brier=0.207983
H=25 K=15 a=0.55 b=1 | train_logloss=0.629165 train_brier=0.219727 | test_logloss=0.599304 test_brier=0.204657
H=25 K=15 a=0.6 b=0.8 | train_logloss=0.634962 train_brier=0.222157 | test_logloss=0.612910 test_brier=0.211064
H=25 K=15 a=0.6 b=0.9 | train_logloss=0.631216 train_brier=0.220592 | test_logloss=0.605270 test_brier=0.207497
H=25 K=15 a=0.6 b=1 | train_logloss=0.629395 train_brier=0.219846 | test_logloss=0.598988 test_brier=0.204477
H=25 K=15 a=0.65 b=0.8 | train_logloss=0.634908 train_brier=0.222169 | test_logloss=0.611283 test_brier=0.210325
H=25 K=15 a=0.65 b=0.9 | train_logloss=0.631377 train_brier=0.220696 | test_logloss=0.604338 test_brier=0.207060
H=25 K=15 a=0.65 b=1 | train_logloss=0.629804 train_brier=0.220041 | test_logloss=0.598845 test_brier=0.204363
H=25 K=20 a=0.45 b=0.8 | train_logloss=0.632105 train_brier=0.220904 | test_logloss=0.609303 test_brier=0.209373
H=25 K=20 a=0.45 b=0.9 | train_logloss=0.629540 train_brier=0.219860 | test_logloss=0.600939 test_brier=0.205467
H=25 K=20 a=0.45 b=1 | train_logloss=0.629562 train_brier=0.219848 | test_logloss=0.594299 test_brier=0.202206
H=25 K=20 a=0.5 b=0.8 | train_logloss=0.631819 train_brier=0.220799 | test_logloss=0.607969 test_brier=0.208758
H=25 K=20 a=0.5 b=0.9 | train_logloss=0.629426 train_brier=0.219825 | test_logloss=0.600223 test_brier=0.205125
H=25 K=20 a=0.5 b=1 | train_logloss=0.629638 train_brier=0.219878 | test_logloss=0.594226 test_brier=0.202129
H=25 K=20 a=0.55 b=0.8 | train_logloss=0.631663 train_brier=0.220756 | test_logloss=0.606733 test_brier=0.208190
H=25 K=20 a=0.55 b=0.9 | train_logloss=0.629460 train_brier=0.219858 | test_logloss=0.599649 test_brier=0.204843
H=25 K=20 a=0.55 b=1 | train_logloss=0.629879 train_brier=0.219978 | test_logloss=0.594354 test_brier=0.202133
H=25 K=20 a=0.6 b=0.8 | train_logloss=0.631645 train_brier=0.220778 | test_logloss=0.605604 test_brier=0.207670
H=25 K=20 a=0.6 b=0.9 | train_logloss=0.629654 train_brier=0.219960 | test_logloss=0.599233 test_brier=0.204625
H=25 K=20 a=0.6 b=1 | train_logloss=0.630297 train_brier=0.220152 | test_logloss=0.594682 test_brier=0.202213
H=25 K=20 a=0.65 b=0.8 | train_logloss=0.631780 train_brier=0.220869 | test_logloss=0.604585 test_brier=0.207199
H=25 K=20 a=0.65 b=0.9 | train_logloss=0.630017 train_brier=0.220136 | test_logloss=0.598984 test_brier=0.204471
H=25 K=20 a=0.65 b=1 | train_logloss=0.630909 train_brier=0.220402 | test_logloss=0.595225 test_brier=0.202369
H=25 K=25 a=0.45 b=0.8 | train_logloss=0.630269 train_brier=0.220167 | test_logloss=0.603123 test_brier=0.206501
H=25 K=25 a=0.45 b=0.9 | train_logloss=0.629470 train_brier=0.219838 | test_logloss=0.595944 test_brier=0.203050
H=25 K=25 a=0.45 b=1 | train_logloss=0.631966 train_brier=0.220716 | test_logloss=0.591183 test_brier=0.200405
H=25 K=25 a=0.5 b=0.8 | train_logloss=0.630101 train_brier=0.220110 | test_logloss=0.602196 test_brier=0.206069
H=25 K=25 a=0.5 b=0.9 | train_logloss=0.629480 train_brier=0.219844 | test_logloss=0.595648 test_brier=0.202885
H=25 K=25 a=0.5 b=1 | train_logloss=0.632155 train_brier=0.220773 | test_logloss=0.591480 test_brier=0.200469
H=25 K=25 a=0.55 b=0.8 | train_logloss=0.630074 train_brier=0.220117 | test_logloss=0.601402 test_brier=0.205695
H=25 K=25 a=0.55 b=0.9 | train_logloss=0.629649 train_brier=0.219920 | test_logloss=0.595534 test_brier=0.202794
H=25 K=25 a=0.55 b=1 | train_logloss=0.632519 train_brier=0.220901 | test_logloss=0.592015 test_brier=0.200630
H=25 K=25 a=0.6 b=0.8 | train_logloss=0.630198 train_brier=0.220193 | test_logloss=0.600749 test_brier=0.205381
H=25 K=25 a=0.6 b=0.9 | train_logloss=0.629982 train_brier=0.220065 | test_logloss=0.595605 test_brier=0.202775
H=25 K=25 a=0.6 b=1 | train_logloss=0.633065 train_brier=0.221101 | test_logloss=0.592787 test_brier=0.200879
H=25 K=25 a=0.65 b=0.8 | train_logloss=0.630479 train_brier=0.220338 | test_logloss=0.600253 test_brier=0.205130
H=25 K=25 a=0.65 b=0.9 | train_logloss=0.630491 train_brier=0.220282 | test_logloss=0.595879 test_brier=0.202831
H=25 K=25 a=0.65 b=1 | train_logloss=0.633806 train_brier=0.221373 | test_logloss=0.593804 test_brier=0.201216
H=25 K=30 a=0.45 b=0.8 | train_logloss=0.629702 train_brier=0.219951 | test_logloss=0.598672 test_brier=0.204392
H=25 K=30 a=0.45 b=0.9 | train_logloss=0.630676 train_brier=0.220287 | test_logloss=0.592797 test_brier=0.201389
H=25 K=30 a=0.45 b=1 | train_logloss=0.635684 train_brier=0.222001 | test_logloss=0.590036 test_brier=0.199342
H=25 K=30 a=0.5 b=0.8 | train_logloss=0.629631 train_brier=0.219928 | test_logloss=0.598091 test_brier=0.204109
H=25 K=30 a=0.5 b=0.9 | train_logloss=0.630780 train_brier=0.220319 | test_logloss=0.592808 test_brier=0.201345
H=25 K=30 a=0.5 b=1 | train_logloss=0.635955 train_brier=0.222073 | test_logloss=0.590602 test_brier=0.199498
H=25 K=30 a=0.55 b=0.8 | train_logloss=0.629706 train_brier=0.219971 | test_logloss=0.597664 test_brier=0.203892
H=25 K=30 a=0.55 b=0.9 | train_logloss=0.631044 train_brier=0.220420 | test_logloss=0.593042 test_brier=0.201391
H=25 K=30 a=0.55 b=1 | train_logloss=0.636404 train_brier=0.222213 | test_logloss=0.591419 test_brier=0.199756
H=25 K=30 a=0.6 b=0.8 | train_logloss=0.629937 train_brier=0.220082 | test_logloss=0.597407 test_brier=0.203743
H=25 K=30 a=0.6 b=0.9 | train_logloss=0.631480 train_brier=0.220589 | test_logloss=0.593493 test_brier=0.201521
H=25 K=30 a=0.6 b=1 | train_logloss=0.637038 train_brier=0.222422 | test_logloss=0.592507 test_brier=0.200119
H=25 K=30 a=0.65 b=0.8 | train_logloss=0.630334 train_brier=0.220262 | test_logloss=0.597329 test_brier=0.203662
H=25 K=30 a=0.65 b=0.9 | train_logloss=0.632100 train_brier=0.220830 | test_logloss=0.594167 test_brier=0.201732
H=25 K=30 a=0.65 b=1 | train_logloss=0.637869 train_brier=0.222700 | test_logloss=0.593865 test_brier=0.200578
H=25 K=35 a=0.45 b=0.8 | train_logloss=0.630005 train_brier=0.220071 | test_logloss=0.595460 test_brier=0.202804
H=25 K=35 a=0.45 b=0.9 | train_logloss=0.632768 train_brier=0.221037 | test_logloss=0.590971 test_brier=0.200239
H=25 K=35 a=0.45 b=1 | train_logloss=0.640321 train_brier=0.223541 | test_logloss=0.590301 test_brier=0.198789
H=25 K=35 a=0.5 b=0.8 | train_logloss=0.630015 train_brier=0.220074 | test_logloss=0.595147 test_brier=0.202633
H=25 K=35 a=0.5 b=0.9 | train_logloss=0.632938 train_brier=0.221083 | test_logloss=0.591228 test_brier=0.200286
H=25 K=35 a=0.5 b=1 | train_logloss=0.640653 train_brier=0.223619 | test_logloss=0.591081 test_brier=0.199011
H=25 K=35 a=0.55 b=0.8 | train_logloss=0.630177 train_brier=0.220144 | test_logloss=0.595028 test_brier=0.202542
H=25 K=35 a=0.55 b=0.9 | train_logloss=0.633277 train_brier=0.221198 | test_logloss=0.591714 test_brier=0.200426
H=25 K=35 a=0.55 b=1 | train_logloss=0.641162 train_brier=0.223762 | test_logloss=0.592117 test_brier=0.199332
H=25 K=35 a=0.6 b=0.8 | train_logloss=0.630496 train_brier=0.220279 | test_logloss=0.595098 test_brier=0.202526
H=25 K=35 a=0.6 b=0.9 | train_logloss=0.633791 train_brier=0.221380 | test_logloss=0.592448 test_brier=0.200662
H=25 K=35 a=0.6 b=1 | train_logloss=0.641863 train_brier=0.223973 | test_logloss=0.593423 test_brier=0.199757
H=25 K=35 a=0.65 b=0.8 | train_logloss=0.630982 train_brier=0.220481 | test_logloss=0.595368 test_brier=0.202584
H=25 K=35 a=0.65 b=0.9 | train_logloss=0.634487 train_brier=0.221630 | test_logloss=0.593426 test_brier=0.200986
H=25 K=35 a=0.65 b=1 | train_logloss=0.642765 train_brier=0.224250 | test_logloss=0.595033 test_brier=0.200298
H=30 K=15 a=0.45 b=0.8 | train_logloss=0.634478 train_brier=0.221849 | test_logloss=0.619113 test_brier=0.213916
H=30 K=15 a=0.45 b=0.9 | train_logloss=0.630164 train_brier=0.220038 | test_logloss=0.609638 test_brier=0.209473
H=30 K=15 a=0.45 b=1 | train_logloss=0.627673 train_brier=0.219042 | test_logloss=0.601233 test_brier=0.205496
H=30 K=15 a=0.5 b=0.8 | train_logloss=0.634045 train_brier=0.221676 | test_logloss=0.617298 test_brier=0.213067
H=30 K=15 a=0.5 b=0.9 | train_logloss=0.629885 train_brier=0.219937 | test_logloss=0.608359 test_brier=0.208872
H=30 K=15 a=0.5 b=1 | train_logloss=0.627575 train_brier=0.219014 | test_logloss=0.600584 test_brier=0.205170
H=30 K=15 a=0.55 b=0.8 | train_logloss=0.633726 train_brier=0.221561 | test_logloss=0.615522 test_brier=0.212241
H=30 K=15 a=0.55 b=0.9 | train_logloss=0.629739 train_brier=0.219900 | test_logloss=0.607177 test_brier=0.208315
H=30 K=15 a=0.55 b=1 | train_logloss=0.627632 train_brier=0.219058 | test_logloss=0.600085 test_brier=0.204905
H=30 K=15 a=0.6 b=0.8 | train_logloss=0.633531 train_brier=0.221505 | test_logloss=0.613806 test_brier=0.211447
H=30 K=15 a=0.6 b=0.9 | train_logloss=0.629738 train_brier=0.219931 | test_logloss=0.606098 test_brier=0.207805
H=30 K=15 a=0.6 b=1 | train_logloss=0.627856 train_brier=0.219174 | test_logloss=0.599744 test_brier=0.204704
H=30 K=15 a=0.65 b=0.8 | train_logloss=0.633472 train_brier=0.221515 | test_logloss=0.612158 test_brier=0.210691
H=30 K=15 a=0.65 b=0.9 | train_logloss=0.629895 train_brier=0.220034 | test_logloss=0.605137 test_brier=0.207345
H=30 K=15 a=0.65 b=1 | train_logloss=0.628259 train_brier=0.219368 | test_logloss=0.599567 test_brier=0.204565
H=30 K=20 a=0.45 b=0.8 | train_logloss=0.630641 train_brier=0.220247 | test_logloss=0.610214 test_brier=0.209751
H=30 K=20 a=0.45 b=0.9 | train_logloss=0.628021 train_brier=0.219194 | test_logloss=0.601784 test_brier=0.205769
H=30 K=20 a=0.45 b=1 | train_logloss=0.627966 train_brier=0.219165 | test_logloss=0.595056 test_brier=0.202419
H=30 K=20 a=0.5 b=0.8 | train_logloss=0.630352 train_brier=0.220141 | test_logloss=0.608859 test_brier=0.209118
H=30 K=20 a=0.5 b=0.9 | train_logloss=0.627902 train_brier=0.219157 | test_logloss=0.601041 test_brier=0.205405
H=30 K=20 a=0.5 b=1 | train_logloss=0.628038 train_brier=0.219194 | test_logloss=0.594947 test_brier=0.202317
H=30 K=20 a=0.55 b=0.8 | train_logloss=0.630194 train_brier=0.220097 | test_logloss=0.607595 test_brier=0.208527
H=30 K=20 a=0.55 b=0.9 | train_logloss=0.627933 train_brier=0.219188 | test_logloss=0.600443 test_brier=0.205102
H=30 K=20 a=0.55 b=1 | train_logloss=0.628272 train_brier=0.219293 | test_logloss=0.595035 test_brier=0.202295
H=30 K=20 a=0.6 b=0.8 | train_logloss=0.630173 train_brier=0.220119 | test_logloss=0.606434 test_brier=0.207983
H=30 K=20 a=0.6 b=0.9 | train_logloss=0.628122 train_brier=0.219290 | test_logloss=0.599998 test_brier=0.204861
H=30 K=20 a=0.6 b=1 | train_logloss=0.628682 train_brier=0.219465 | test_logloss=0.595329 test_brier=0.202351
H=30 K=20 a=0.65 b=0.8 | train_logloss=0.630302 train_brier=0.220208 | test_logloss=0.605392 test_brier=0.207492
H=30 K=20 a=0.65 b=0.9 | train_logloss=0.628481 train_brier=0.219465 | test_logloss=0.599717 test_brier=0.204683
H=30 K=20 a=0.65 b=1 | train_logloss=0.629276 train_brier=0.219709 | test_logloss=0.595840 test_brier=0.202485
H=30 K=25 a=0.45 b=0.8 | train_logloss=0.628768 train_brier=0.219504 | test_logloss=0.603979 test_brier=0.206822
H=30 K=25 a=0.45 b=0.9 | train_logloss=0.627904 train_brier=0.219162 | test_logloss=0.596739 test_brier=0.203295
H=30 K=25 a=0.45 b=1 | train_logloss=0.630292 train_brier=0.220013 | test_logloss=0.591866 test_brier=0.200556
H=30 K=25 a=0.5 b=0.8 | train_logloss=0.628600 train_brier=0.219447 | test_logloss=0.603030 test_brier=0.206370
H=30 K=25 a=0.5 b=0.9 | train_logloss=0.627910 train_brier=0.219168 | test_logloss=0.596410 test_brier=0.203106
H=30 K=25 a=0.5 b=1 | train_logloss=0.630476 train_brier=0.220071 | test_logloss=0.592137 test_brier=0.200603
H=30 K=25 a=0.55 b=0.8 | train_logloss=0.628569 train_brier=0.219453 | test_logloss=0.602209 test_brier=0.205975
H=30 K=25 a=0.55 b=0.9 | train_logloss=0.628068 train_brier=0.219240 | test_logloss=0.596266 test_brier=0.202992
H=30 K=25 a=0.55 b=1 | train_logloss=0.630832 train_brier=0.220198 | test_logloss=0.592641 test_brier=0.200743
H=30 K=25 a=0.6 b=0.8 | train_logloss=0.628687 train_brier=0.219527 | test_logloss=0.601528 test_brier=0.205638
H=30 K=25 a=0.6 b=0.9 | train_logloss=0.628391 train_brier=0.219382 | test_logloss=0.596309 test_brier=0.202951
H=30 K=25 a=0.6 b=1 | train_logloss=0.631370 train_brier=0.220396 | test_logloss=0.593383 test_brier=0.200973
H=30 K=25 a=0.65 b=0.8 | train_logloss=0.628965 train_brier=0.219671 | test_logloss=0.600995 test_brier=0.205360
H=30 K=25 a=0.65 b=0.9 | train_logloss=0.628892 train_brier=0.219597 | test_logloss=0.596545 test_brier=0.202981
H=30 K=25 a=0.65 b=1 | train_logloss=0.632098 train_brier=0.220666 | test_logloss=0.594371 test_brier=0.201290
H=30 K=30 a=0.45 b=0.8 | train_logloss=0.628162 train_brier=0.219279 | test_logloss=0.599505 test_brier=0.204674
H=30 K=30 a=0.45 b=0.9 | train_logloss=0.629054 train_brier=0.219597 | test_logloss=0.593535 test_brier=0.201583
H=30 K=30 a=0.45 b=1 | train_logloss=0.633924 train_brier=0.221276 | test_logloss=0.590641 test_brier=0.199437
H=30 K=30 a=0.5 b=0.8 | train_logloss=0.628089 train_brier=0.219256 | test_logloss=0.598890 test_brier=0.204367
H=30 K=30 a=0.5 b=0.9 | train_logloss=0.629152 train_brier=0.219629 | test_logloss=0.593523 test_brier=0.201521
H=30 K=30 a=0.5 b=1 | train_logloss=0.634188 train_brier=0.221348 | test_logloss=0.591191 test_brier=0.199584
H=30 K=30 a=0.55 b=0.8 | train_logloss=0.628160 train_brier=0.219298 | test_logloss=0.598442 test_brier=0.204131
H=30 K=30 a=0.55 b=0.9 | train_logloss=0.629408 train_brier=0.219727 | test_logloss=0.593724 test_brier=0.201546
H=30 K=30 a=0.55 b=1 | train_logloss=0.634626 train_brier=0.221487 | test_logloss=0.591985 test_brier=0.199827
H=30 K=30 a=0.6 b=0.8 | train_logloss=0.628386 train_brier=0.219407 | test_logloss=0.598158 test_brier=0.203960
H=30 K=30 a=0.6 b=0.9 | train_logloss=0.629836 train_brier=0.219895 | test_logloss=0.594147 test_brier=0.201656
H=30 K=30 a=0.6 b=1 | train_logloss=0.635252 train_brier=0.221695 | test_logloss=0.593036 test_brier=0.200168
H=30 K=30 a=0.65 b=0.8 | train_logloss=0.628775 train_brier=0.219585 | test_logloss=0.598048 test_brier=0.203856
H=30 K=30 a=0.65 b=0.9 | train_logloss=0.630445 train_brier=0.220133 | test_logloss=0.594788 test_brier=0.201845
H=30 K=30 a=0.65 b=1 | train_logloss=0.636074 train_brier=0.221973 | test_logloss=0.594365 test_brier=0.200610
H=30 K=35 a=0.45 b=0.8 | train_logloss=0.628430 train_brier=0.219392 | test_logloss=0.596258 test_brier=0.203049
H=30 K=35 a=0.45 b=0.9 | train_logloss=0.631087 train_brier=0.220331 | test_logloss=0.591648 test_brier=0.200387
H=30 K=35 a=0.45 b=1 | train_logloss=0.638473 train_brier=0.222794 | test_logloss=0.590827 test_brier=0.198833
H=30 K=35 a=0.5 b=0.8 | train_logloss=0.628436 train_brier=0.219394 | test_logloss=0.595922 test_brier=0.202858
H=30 K=35 a=0.5 b=0.9 | train_logloss=0.631253 train_brier=0.220378 | test_logloss=0.591887 test_brier=0.200421
H=30 K=35 a=0.5 b=1 | train_logloss=0.638800 train_brier=0.222873 | test_logloss=0.591589 test_brier=0.199045
H=30 K=35 a=0.55 b=0.8 | train_logloss=0.628589 train_brier=0.219461 | test_logloss=0.595774 test_brier=0.202746
H=30 K=35 a=0.55 b=0.9 | train_logloss=0.631584 train_brier=0.220492 | test_logloss=0.592345 test_brier=0.200541
H=30 K=35 a=0.55 b=1 | train_logloss=0.639307 train_brier=0.223019 | test_logloss=0.592606 test_brier=0.199358
H=30 K=35 a=0.6 b=0.8 | train_logloss=0.628899 train_brier=0.219593 | test_logloss=0.595815 test_brier=0.202707
H=30 K=35 a=0.6 b=0.9 | train_logloss=0.632088 train_brier=0.220673 | test_logloss=0.593046 test_brier=0.200757
H=30 K=35 a=0.6 b=1 | train_logloss=0.640000 train_brier=0.223230 | test_logloss=0.593896 test_brier=0.199777
H=30 K=35 a=0.65 b=0.8 | train_logloss=0.629379 train_brier=0.219795 | test_logloss=0.596051 test_brier=0.202742
H=30 K=35 a=0.65 b=0.9 | train_logloss=0.632775 train_brier=0.220922 | test_logloss=0.593997 test_brier=0.201063
H=30 K=35 a=0.65 b=1 | train_logloss=0.640890 train_brier=0.223506 | test_logloss=0.595468 test_brier=0.200296
H=35 K=15 a=0.45 b=0.8 | train_logloss=0.633265 train_brier=0.221306 | test_logloss=0.620273 test_brier=0.214456
H=35 K=15 a=0.45 b=0.9 | train_logloss=0.628904 train_brier=0.219481 | test_logloss=0.610738 test_brier=0.209942
H=35 K=15 a=0.45 b=1 | train_logloss=0.626348 train_brier=0.218467 | test_logloss=0.602261 test_brier=0.205882
H=35 K=15 a=0.5 b=0.8 | train_logloss=0.632828 train_brier=0.221131 | test_logloss=0.618435 test_brier=0.213588
H=35 K=15 a=0.5 b=0.9 | train_logloss=0.628618 train_brier=0.219377 | test_logloss=0.609434 test_brier=0.209320
H=35 K=15 a=0.5 b=1 | train_logloss=0.626246 train_brier=0.218438 | test_logloss=0.601583 test_brier=0.205532
H=35 K=15 a=0.55 b=0.8 | train_logloss=0.632504 train_brier=0.221012 | test_logloss=0.616636 test_brier=0.212743
H=35 K=15 a=0.55 b=0.9 | train_logloss=0.628468 train_brier=0.219338 | test_logloss=0.608220 test_brier=0.208739
H=35 K=15 a=0.55 b=1 | train_logloss=0.626298 train_brier=0.218479 | test_logloss=0.601053 test_brier=0.205243
H=35 K=15 a=0.6 b=0.8 | train_logloss=0.632305 train_brier=0.220954 | test_logloss=0.614893 test_brier=0.211929
H=35 K=15 a=0.6 b=0.9 | train_logloss=0.628461 train_brier=0.219366 | test_logloss=0.607109 test_brier=0.208203
H=35 K=15 a=0.6 b=1 | train_logloss=0.626515 train_brier=0.218593 | test_logloss=0.600682 test_brier=0.205017
H=35 K=15 a=0.65 b=0.8 | train_logloss=0.632240 train_brier=0.220961 | test_logloss=0.613226 test_brier=0.211154
H=35 K=15 a=0.65 b=0.9 | train_logloss=0.628612 train_brier=0.219466 | test_logloss=0.606116 test_brier=0.207718
H=35 K=15 a=0.65 b=1 | train_logloss=0.626911 train_brier=0.218783 | test_logloss=0.600477 test_brier=0.204853
H=35 K=20 a=0.45 b=0.8 | train_logloss=0.629382 train_brier=0.219690 | test_logloss=0.611323 test_brier=0.210229
H=35 K=20 a=0.45 b=0.9 | train_logloss=0.626702 train_brier=0.218620 | test_logloss=0.602814 test_brier=0.206161
H=35 K=20 a=0.45 b=1 | train_logloss=0.626570 train_brier=0.218571 | test_logloss=0.595999 test_brier=0.202718
H=35 K=20 a=0.5 b=0.8 | train_logloss=0.629088 train_brier=0.219582 | test_logloss=0.609943 test_brier=0.209574
H=35 K=20 a=0.5 b=0.9 | train_logloss=0.626581 train_brier=0.218582 | test_logloss=0.602037 test_brier=0.205771
H=35 K=20 a=0.5 b=1 | train_logloss=0.626637 train_brier=0.218599 | test_logloss=0.595853 test_brier=0.202591
H=35 K=20 a=0.55 b=0.8 | train_logloss=0.628926 train_brier=0.219536 | test_logloss=0.608652 test_brier=0.208961
H=35 K=20 a=0.55 b=0.9 | train_logloss=0.626606 train_brier=0.218612 | test_logloss=0.601411 test_brier=0.205445
H=35 K=20 a=0.55 b=1 | train_logloss=0.626867 train_brier=0.218697 | test_logloss=0.595915 test_brier=0.202547
H=35 K=20 a=0.6 b=0.8 | train_logloss=0.628901 train_brier=0.219555 | test_logloss=0.607462 test_brier=0.208394
H=35 K=20 a=0.6 b=0.9 | train_logloss=0.626789 train_brier=0.218710 | test_logloss=0.600936 test_brier=0.205179
H=35 K=20 a=0.6 b=1 | train_logloss=0.627269 train_brier=0.218865 | test_logloss=0.596175 test_brier=0.202578
H=35 K=20 a=0.65 b=0.8 | train_logloss=0.629027 train_brier=0.219642 | test_logloss=0.606384 test_brier=0.207875

,train_start,train_end,test_year,best_H,best_K,best_a,best_b,train_logloss,test_logloss,train_brier,test_brier
0,2015,2019,2020,25,30,0.45,1.0,0.635684,0.590036,0.222001,0.199342
1,2015,2020,2021,30,25,0.50,0.9,0.624223,0.606307,0.217288,0.210808
2,2015,2021,2022,30,15,0.55,1.0,0.621856,0.610734,0.216431,0.211762
3,2015,2022,2023,25,20,0.45,1.0,0.621385,0.600106,0.216292,0.206366
4,2015,2023,2024,35,35,0.45,0.8,0.617760,0.595180,0.214626,0.202870

In [8]:
all_res = pd.concat(all_step_results, ignore_index=True)

# Mean test_logloss across heldout years for each hyperparameter tuple
tuple_means = (
    all_res
    .groupby(["H", "K", "a", "b"], as_index=False)
    .agg(
        mean_test_logloss=("test_logloss", "mean"),
        mean_test_brier=("test_brier", "mean"),
        n_steps=("heldout_year", "nunique"),
    )
    .sort_values(["mean_test_logloss", "mean_test_brier"], ascending=True)
    .reset_index(drop=True)
)

tuple_means.head(30)

     H   K     a    b  mean_test_logloss  mean_test_brier  n_steps
0   25  20  0.45  1.0           0.602076         0.207161        5
1   30  20  0.45  1.0           0.602194         0.207199        5
2   25  30  0.45  0.9           0.602319         0.207204        5
3   25  20  0.50  1.0           0.602377         0.207286        5
4   30  30  0.45  0.9           0.602422         0.207233        5
5   35  20  0.45  1.0           0.602490         0.207314        5
6   30  20  0.50  1.0           0.602493         0.207319        5
7   25  25  0.45  0.9           0.602500         0.207366        5
8   30  25  0.45  0.9           0.602628         0.207413        5
9   25  25  0.50  0.9           0.602632         0.207427        5
10  25  35  0.45  0.8           0.602653         0.207418        5
11  25  30  0.50  0.9           0.602661         0.207334        5
12  35  30  0.45  0.9           0.602708         0.207339        5
13  25  25  0.45  1.0           0.602740         0.207259        5
14  30  25  0.50  0.9           0.602755         0.207469        5
15  25  35  0.50  0.8           0.602757         0.207464        5
16  30  30  0.50  0.9           0.602766         0.207360        5
17  30  35  0.45  0.8           0.602774         0.207463        5
18  35  20  0.50  1.0           0.602784         0.207427        5
19  30  25  0.45  1.0           0.602823         0.207272        5
20  30  35  0.50  0.8           0.602874         0.207503        5
21  35  25  0.45  0.9           0.602929         0.207538        5
22  40  20  0.45  1.0           0.602964         0.207507        5
23  25  20  0.55  1.0           0.602965         0.207519        5
24  25  25  0.55  0.9           0.603032         0.207593        5
25  35  30  0.50  0.9           0.603050         0.207461        5
26  35  25  0.50  0.9           0.603050         0.207586        5
27  35  35  0.45  0.8           0.603070         0.207585        5
28  30  20  0.55  1.0           0.603074         0.207545        5
29  35  25  0.45  1.0           0.603092         0.207361        5

In [9]:
initial_train_years = [2015, 2016, 2017, 2018, 2019]
all_years = list(range(2015, 2025))

H_list = [25, 30, 35]
K_list = [15, 20, 25]
a_list = [0.425, 0.45, 0.475, 0.50]
b_list = [0.9, 0.95, 1.0, 1.05]

# MOV choices:
# - no MOV  -> use_mov=False (b ignored, but we'll include b=0.8 as a placeholder)
# - MOV w/ exponent -> use_mov=True and b in {0.6,0.8,1.0}

all_step_results = []   # stores full res df for each test_year
summary_rows = []

train = initial_train_years.copy()

while True:
    last_train = train[-1]
    idx = all_years.index(last_train)
    if idx + 1 >= len(all_years):
        break
    test_year = all_years[idx + 1]

    print(f"\n=== WALKFORWARD: train={train[0]}-{train[-1]} test={test_year} ===")

    res = run_gridsearch(
        train_years=train,
        test_years=[test_year],
        H_list=H_list,
        K_list=K_list,
        a_list=a_list,
        b_list=b_list,
        verbose=True,
    )

    # tag which held-out year this result corresponds to
    res = res.copy()
    res["heldout_year"] = test_year
    all_step_results.append(res)

    best = res.iloc[0].to_dict()
    summary_rows.append({
        "train_start": train[0],
        "train_end": train[-1],
        "test_year": test_year,
        "best_H": best["H"],
        "best_K": best["K"],
        "best_a": best["a"],
        "best_b": best["b"],
        "train_logloss": best["train_logloss"],
        "test_logloss": best["test_logloss"],
        "train_brier": best["train_brier"],
        "test_brier": best["test_brier"],
    })

    train = train + [test_year]

summary = pd.DataFrame(summary_rows)
summary

=== WALKFORWARD: train=2015-2019 test=2020 ===
H=25 K=15 a=0.425 b=0.9 | train_logloss=0.631815 train_brier=0.220766 | test_logloss=0.609391 test_brier=0.209405
H=25 K=15 a=0.425 b=0.95 | train_logloss=0.630274 train_brier=0.220137 | test_logloss=0.604906 test_brier=0.207321
H=25 K=15 a=0.425 b=1 | train_logloss=0.629299 train_brier=0.219747 | test_logloss=0.600763 test_brier=0.205378
H=25 K=15 a=0.425 b=1.05 | train_logloss=0.628996 train_brier=0.219626 | test_logloss=0.597070 test_brier=0.203606
H=25 K=15 a=0.45 b=0.9 | train_logloss=0.631629 train_brier=0.220693 | test_logloss=0.608730 test_brier=0.209099
H=25 K=15 a=0.45 b=0.95 | train_logloss=0.630129 train_brier=0.220081 | test_logloss=0.604389 test_brier=0.207080
H=25 K=15 a=0.45 b=1 | train_logloss=0.629197 train_brier=0.219708 | test_logloss=0.600398 test_brier=0.205203
H=25 K=15 a=0.45 b=1.05 | train_logloss=0.628943 train_brier=0.219605 | test_logloss=0.596860 test_brier=0.203496
H=25 K=15 a=0.475 b=0.9 | train_logloss=0.631475 train_brier=0.220636 | test_logloss=0.608091 test_brier=0.208804
H=25 K=15 a=0.475 b=0.95 | train_logloss=0.630017 train_brier=0.220041 | test_logloss=0.603901 test_brier=0.206852
H=25 K=15 a=0.475 b=1 | train_logloss=0.629130 train_brier=0.219686 | test_logloss=0.600070 test_brier=0.205044
H=25 K=15 a=0.475 b=1.05 | train_logloss=0.628928 train_brier=0.219602 | test_logloss=0.596693 test_brier=0.203404
H=25 K=15 a=0.5 b=0.9 | train_logloss=0.631352 train_brier=0.220593 | test_logloss=0.607476 test_brier=0.208519
H=25 K=15 a=0.5 b=0.95 | train_logloss=0.629941 train_brier=0.220019 | test_logloss=0.603444 test_brier=0.206637
H=25 K=15 a=0.5 b=1 | train_logloss=0.629102 train_brier=0.219682 | test_logloss=0.599776 test_brier=0.204899
H=25 K=15 a=0.5 b=1.05 | train_logloss=0.628952 train_brier=0.219616 | test_logloss=0.596568 test_brier=0.203329
H=25 K=20 a=0.425 b=0.9 | train_logloss=0.629649 train_brier=0.219902 | test_logloss=0.601351 test_brier=0.205662
H=25 K=20 a=0.425 b=0.95 | train_logloss=0.629232 train_brier=0.219735 | test_logloss=0.597609 test_brier=0.203873
H=25 K=20 a=0.425 b=1 | train_logloss=0.629583 train_brier=0.219859 | test_logloss=0.594411 test_brier=0.202275
H=25 K=20 a=0.425 b=1.05 | train_logloss=0.630865 train_brier=0.220316 | test_logloss=0.591916 test_brier=0.200909
H=25 K=20 a=0.45 b=0.9 | train_logloss=0.629540 train_brier=0.219860 | test_logloss=0.600939 test_brier=0.205467
H=25 K=20 a=0.45 b=0.95 | train_logloss=0.629167 train_brier=0.219709 | test_logloss=0.597349 test_brier=0.203743
H=25 K=20 a=0.45 b=1 | train_logloss=0.629562 train_brier=0.219848 | test_logloss=0.594299 test_brier=0.202206
H=25 K=20 a=0.45 b=1.05 | train_logloss=0.630887 train_brier=0.220318 | test_logloss=0.591949 test_brier=0.200896
H=25 K=20 a=0.475 b=0.9 | train_logloss=0.629465 train_brier=0.219834 | test_logloss=0.600563 test_brier=0.205288
H=25 K=20 a=0.475 b=0.95 | train_logloss=0.629138 train_brier=0.219700 | test_logloss=0.597130 test_brier=0.203630
H=25 K=20 a=0.475 b=1 | train_logloss=0.629580 train_brier=0.219854 | test_logloss=0.594237 test_brier=0.202157
H=25 K=20 a=0.475 b=1.05 | train_logloss=0.630952 train_brier=0.220338 | test_logloss=0.592039 test_brier=0.200907
H=25 K=20 a=0.5 b=0.9 | train_logloss=0.629426 train_brier=0.219825 | test_logloss=0.600223 test_brier=0.205125
H=25 K=20 a=0.5 b=0.95 | train_logloss=0.629147 train_brier=0.219708 | test_logloss=0.596953 test_brier=0.203535
H=25 K=20 a=0.5 b=1 | train_logloss=0.629638 train_brier=0.219878 | test_logloss=0.594226 test_brier=0.202129
H=25 K=20 a=0.5 b=1.05 | train_logloss=0.631059 train_brier=0.220375 | test_logloss=0.592185 test_brier=0.200940
H=25 K=25 a=0.425 b=0.9 | train_logloss=0.629520 train_brier=0.219859 | test_logloss=0.596163 test_brier=0.203163
H=25 K=25 a=0.425 b=0.95 | train_logloss=0.630233 train_brier=0.220114 | test_logloss=0.593262 test_brier=0.201665
H=25 K=25 a=0.425 b=1 | train_logloss=0.631933 train_brier=0.220712 | test_logloss=0.591118 test_brier=0.200406
H=25 K=25 a=0.425 b=1.05 | train_logloss=0.634830 train_brier=0.221704 | test_logloss=0.589916 test_brier=0.199429
H=25 K=25 a=0.45 b=0.9 | train_logloss=0.629470 train_brier=0.219838 | test_logloss=0.595944 test_brier=0.203050
H=25 K=25 a=0.45 b=0.95 | train_logloss=0.630225 train_brier=0.220106 | test_logloss=0.593186 test_brier=0.201609
H=25 K=25 a=0.45 b=1 | train_logloss=0.631966 train_brier=0.220716 | test_logloss=0.591183 test_brier=0.200405
H=25 K=25 a=0.45 b=1.05 | train_logloss=0.634904 train_brier=0.221717 | test_logloss=0.590113 test_brier=0.199474
H=25 K=25 a=0.475 b=0.9 | train_logloss=0.629457 train_brier=0.219833 | test_logloss=0.595774 test_brier=0.202958
H=25 K=25 a=0.475 b=0.95 | train_logloss=0.630256 train_brier=0.220114 | test_logloss=0.593161 test_brier=0.201575
H=25 K=25 a=0.475 b=1 | train_logloss=0.632039 train_brier=0.220735 | test_logloss=0.591303 test_brier=0.200425
H=25 K=25 a=0.475 b=1.05 | train_logloss=0.635021 train_brier=0.221747 | test_logloss=0.590371 test_brier=0.199544
H=25 K=25 a=0.5 b=0.9 | train_logloss=0.629480 train_brier=0.219844 | test_logloss=0.595648 test_brier=0.202885
H=25 K=25 a=0.5 b=0.95 | train_logloss=0.630327 train_brier=0.220140 | test_logloss=0.593193 test_brier=0.201565
H=25 K=25 a=0.5 b=1 | train_logloss=0.632155 train_brier=0.220773 | test_logloss=0.591480 test_brier=0.200469
H=25 K=25 a=0.5 b=1.05 | train_logloss=0.635182 train_brier=0.221795 | test_logloss=0.590688 test_brier=0.199638
H=30 K=15 a=0.425 b=0.9 | train_logloss=0.630352 train_brier=0.220112 | test_logloss=0.610311 test_brier=0.209789
H=30 K=15 a=0.425 b=0.95 | train_logloss=0.628786 train_brier=0.219477 | test_logloss=0.605792 test_brier=0.207666
H=30 K=15 a=0.425 b=1 | train_logloss=0.627778 train_brier=0.219081 | test_logloss=0.601613 test_brier=0.205682
H=30 K=15 a=0.425 b=1.05 | train_logloss=0.627437 train_brier=0.218951 | test_logloss=0.597874 test_brier=0.203863
H=30 K=15 a=0.45 b=0.9 | train_logloss=0.630164 train_brier=0.220038 | test_logloss=0.609638 test_brier=0.209473
H=30 K=15 a=0.45 b=0.95 | train_logloss=0.628638 train_brier=0.219421 | test_logloss=0.605262 test_brier=0.207414
H=30 K=15 a=0.45 b=1 | train_logloss=0.627673 train_brier=0.219042 | test_logloss=0.601233 test_brier=0.205496
H=30 K=15 a=0.45 b=1.05 | train_logloss=0.627382 train_brier=0.218930 | test_logloss=0.597649 test_brier=0.203742
H=30 K=15 a=0.475 b=0.9 | train_logloss=0.630009 train_brier=0.219980 | test_logloss=0.608987 test_brier=0.209167
H=30 K=15 a=0.475 b=0.95 | train_logloss=0.628525 train_brier=0.219381 | test_logloss=0.604761 test_brier=0.207175
H=30 K=15 a=0.475 b=1 | train_logloss=0.627605 train_brier=0.219019 | test_logloss=0.600891 test_brier=0.205325
H=30 K=15 a=0.475 b=1.05 | train_logloss=0.627365 train_brier=0.218926 | test_logloss=0.597469 test_brier=0.203639
H=30 K=15 a=0.5 b=0.9 | train_logloss=0.629885 train_brier=0.219937 | test_logloss=0.608359 test_brier=0.208872
H=30 K=15 a=0.5 b=0.95 | train_logloss=0.628447 train_brier=0.219357 | test_logloss=0.604291 test_brier=0.206950
H=30 K=15 a=0.5 b=1 | train_logloss=0.627575 train_brier=0.219014 | test_logloss=0.600584 test_brier=0.205170
H=30 K=15 a=0.5 b=1.05 | train_logloss=0.627387 train_brier=0.218941 | test_logloss=0.597331 test_brier=0.203554
H=30 K=20 a=0.425 b=0.9 | train_logloss=0.628133 train_brier=0.219237 | test_logloss=0.602210 test_brier=0.205975
H=30 K=20 a=0.425 b=0.95 | train_logloss=0.627682 train_brier=0.219062 | test_logloss=0.598426 test_brier=0.204142
H=30 K=20 a=0.425 b=1 | train_logloss=0.627988 train_brier=0.219176 | test_logloss=0.595186 test_brier=0.202501
H=30 K=20 a=0.425 b=1.05 | train_logloss=0.629215 train_brier=0.219620 | test_logloss=0.592630 test_brier=0.201084
H=30 K=20 a=0.45 b=0.9 | train_logloss=0.628021 train_brier=0.219194 | test_logloss=0.601784 test_brier=0.205769
H=30 K=20 a=0.45 b=0.95 | train_logloss=0.627615 train_brier=0.219036 | test_logloss=0.598148 test_brier=0.203999
H=30 K=20 a=0.45 b=1 | train_logloss=0.627966 train_brier=0.219165 | test_logloss=0.595056 test_brier=0.202419
H=30 K=20 a=0.45 b=1.05 | train_logloss=0.629236 train_brier=0.219621 | test_logloss=0.592649 test_brier=0.201061
H=30 K=20 a=0.475 b=0.9 | train_logloss=0.627943 train_brier=0.219167 | test_logloss=0.601395 test_brier=0.205580
H=30 K=20 a=0.475 b=0.95 | train_logloss=0.627584 train_brier=0.219027 | test_logloss=0.597917 test_brier=0.203876
H=30 K=20 a=0.475 b=1 | train_logloss=0.627982 train_brier=0.219171 | test_logloss=0.594975 test_brier=0.202357
H=30 K=20 a=0.475 b=1.05 | train_logloss=0.629298 train_brier=0.219641 | test_logloss=0.592718 test_brier=0.201059
H=30 K=20 a=0.5 b=0.9 | train_logloss=0.627902 train_brier=0.219157 | test_logloss=0.601041 test_brier=0.205405
H=30 K=20 a=0.5 b=0.95 | train_logloss=0.627589 train_brier=0.219033 | test_logloss=0.597727 test_brier=0.203771
H=30 K=20 a=0.5 b=1 | train_logloss=0.628038 train_brier=0.219194 | test_logloss=0.594947 test_brier=0.202317
H=30 K=20 a=0.5 b=1.05 | train_logloss=0.629401 train_brier=0.219678 | test_logloss=0.592846 test_brier=0.201081
H=30 K=25 a=0.425 b=0.9 | train_logloss=0.627955 train_brier=0.219184 | test_logloss=0.596972 test_brier=0.203419
H=30 K=25 a=0.425 b=0.95 | train_logloss=0.628623 train_brier=0.219427 | test_logloss=0.594016 test_brier=0.201872
H=30 K=25 a=0.425 b=1 | train_logloss=0.630263 train_brier=0.220011 | test_logloss=0.591811 test_brier=0.200565
H=30 K=25 a=0.425 b=1.05 | train_logloss=0.633084 train_brier=0.220983 | test_logloss=0.590538 test_brier=0.199536
H=30 K=25 a=0.45 b=0.9 | train_logloss=0.627904 train_brier=0.219162 | test_logloss=0.596739 test_brier=0.203295
H=30 K=25 a=0.45 b=0.95 | train_logloss=0.628612 train_brier=0.219419 | test_logloss=0.593930 test_brier=0.201808
H=30 K=25 a=0.45 b=1 | train_logloss=0.630292 train_brier=0.220013 | test_logloss=0.591866 test_brier=0.200556
H=30 K=25 a=0.45 b=1.05 | train_logloss=0.633154 train_brier=0.220995 | test_logloss=0.590730 test_brier=0.199578
H=30 K=25 a=0.475 b=0.9 | train_logloss=0.627888 train_brier=0.219157 | test_logloss=0.596549 test_brier=0.203190
H=30 K=25 a=0.475 b=0.95 | train_logloss=0.628641 train_brier=0.219427 | test_logloss=0.593892 test_brier=0.201764
H=30 K=25 a=0.475 b=1 | train_logloss=0.630363 train_brier=0.220033 | test_logloss=0.591974 test_brier=0.200568
H=30 K=25 a=0.475 b=1.05 | train_logloss=0.633266 train_brier=0.221024 | test_logloss=0.590978 test_brier=0.199641
H=30 K=25 a=0.5 b=0.9 | train_logloss=0.627910 train_brier=0.219168 | test_logloss=0.596410 test_brier=0.203106
H=30 K=25 a=0.5 b=0.95 | train_logloss=0.628708 train_brier=0.219453 | test_logloss=0.593904 test_brier=0.201741
H=30 K=25 a=0.5 b=1 | train_logloss=0.630476 train_brier=0.220071 | test_logloss=0.592137 test_brier=0.200603
H=30 K=25 a=0.5 b=1.05 | train_logloss=0.633423 train_brier=0.221071 | test_logloss=0.591284 test_brier=0.199729
H=35 K=15 a=0.425 b=0.9 | train_logloss=0.629096 train_brier=0.219557 | test_logloss=0.611424 test_brier=0.210269
H=35 K=15 a=0.425 b=0.95 | train_logloss=0.627499 train_brier=0.218914 | test_logloss=0.606868 test_brier=0.208105
H=35 K=15 a=0.425 b=1 | train_logloss=0.626454 train_brier=0.218507 | test_logloss=0.602658 test_brier=0.206081
H=35 K=15 a=0.425 b=1.05 | train_logloss=0.626079 train_brier=0.218368 | test_logloss=0.598880 test_brier=0.204218
H=35 K=15 a=0.45 b=0.9 | train_logloss=0.628904 train_brier=0.219481 | test_logloss=0.610738 test_brier=0.209942
H=35 K=15 a=0.45 b=0.95 | train_logloss=0.627348 train_brier=0.218856 | test_logloss=0.606323 test_brier=0.207841
H=35 K=15 a=0.45 b=1 | train_logloss=0.626348 train_brier=0.218467 | test_logloss=0.602261 test_brier=0.205882
H=35 K=15 a=0.45 b=1.05 | train_logloss=0.626021 train_brier=0.218346 | test_logloss=0.598635 test_brier=0.204083
H=35 K=15 a=0.475 b=0.9 | train_logloss=0.628744 train_brier=0.219421 | test_logloss=0.610075 test_brier=0.209626
H=35 K=15 a=0.475 b=0.95 | train_logloss=0.627232 train_brier=0.218815 | test_logloss=0.605810 test_brier=0.207592
H=35 K=15 a=0.475 b=1 | train_logloss=0.626279 train_brier=0.218444 | test_logloss=0.601904 test_brier=0.205699
H=35 K=15 a=0.475 b=1.05 | train_logloss=0.626001 train_brier=0.218341 | test_logloss=0.598436 test_brier=0.203966
H=35 K=15 a=0.5 b=0.9 | train_logloss=0.628618 train_brier=0.219377 | test_logloss=0.609434 test_brier=0.209320
H=35 K=15 a=0.5 b=0.95 | train_logloss=0.627151 train_brier=0.218790 | test_logloss=0.605326 test_brier=0.207354
H=35 K=15 a=0.5 b=1 | train_logloss=0.626246 train_brier=0.218438 | test_logloss=0.601583 test_brier=0.205532
H=35 K=15 a=0.5 b=1.05 | train_logloss=0.626018 train_brier=0.218353 | test_logloss=0.598280 test_brier=0.203867
H=35 K=20 a=0.425 b=0.9 | train_logloss=0.626816 train_brier=0.218664 | test_logloss=0.603258 test_brier=0.206380
H=35 K=20 a=0.425 b=0.95 | train_logloss=0.626333 train_brier=0.218482 | test_logloss=0.599439 test_brier=0.204505
H=35 K=20 a=0.425 b=1 | train_logloss=0.626595 train_brier=0.218582 | test_logloss=0.596144 test_brier=0.202812
H=35 K=20 a=0.425 b=1.05 | train_logloss=0.627769 train_brier=0.219011 | test_logloss=0.593534 test_brier=0.201345
H=35 K=20 a=0.45 b=0.9 | train_logloss=0.626702 train_brier=0.218620 | test_logloss=0.602814 test_brier=0.206161
H=35 K=20 a=0.45 b=0.95 | train_logloss=0.626262 train_brier=0.218454 | test_logloss=0.599146 test_brier=0.204350
H=35 K=20 a=0.45 b=1 | train_logloss=0.626570 train_brier=0.218571 | test_logloss=0.595999 test_brier=0.202718
H=35 K=20 a=0.45 b=1.05 | train_logloss=0.627788 train_brier=0.219012 | test_logloss=0.593536 test_brier=0.201310
H=35 K=20 a=0.475 b=0.9 | train_logloss=0.626624 train_brier=0.218593 | test_logloss=0.602406 test_brier=0.205958
H=35 K=20 a=0.475 b=0.95 | train_logloss=0.626227 train_brier=0.218443 | test_logloss=0.598891 test_brier=0.204211
H=35 K=20 a=0.475 b=1 | train_logloss=0.626583 train_brier=0.218576 | test_logloss=0.595902 test_brier=0.202645
H=35 K=20 a=0.475 b=1.05 | train_logloss=0.627847 train_brier=0.219031 | test_logloss=0.593592 test_brier=0.201298
H=35 K=20 a=0.5 b=0.9 | train_logloss=0.626581 train_brier=0.218582 | test_logloss=0.602037 test_brier=0.205771
H=35 K=20 a=0.5 b=0.95 | train_logloss=0.626230 train_brier=0.218449 | test_logloss=0.598685 test_brier=0.204093
H=35 K=20 a=0.5 b=1 | train_logloss=0.626637 train_brier=0.218599 | test_logloss=0.595853 test_brier=0.202591
H=35 K=20 a=0.5 b=1.05 | train_logloss=0.627948 train_brier=0.219067 | test_logloss=0.593699 test_brier=0.201306
H=35 K=25 a=0.425 b=0.9 | train_logloss=0.626589 train_brier=0.218597 | test_logloss=0.597961 test_brier=0.203760
H=35 K=25 a=0.425 b=0.95 | train_logloss=0.627210 train_brier=0.218828 | test_logloss=0.594955 test_brier=0.202165
H=35 K=25 a=0.425 b=1 | train_logloss=0.628796 train_brier=0.219395 | test_logloss=0.592690 test_brier=0.200805
H=35 K=25 a=0.425 b=1.05 | train_logloss=0.631544 train_brier=0.220345 | test_logloss=0.591353 test_brier=0.199726
H=35 K=25 a=0.45 b=0.9 | train_logloss=0.626535 train_brier=0.218575 | test_logloss=0.597714 test_brier=0.203625
H=35 K=25 a=0.45 b=0.95 | train_logloss=0.627199 train_brier=0.218819 | test_logloss=0.594855 test_brier=0.202090
H=35 K=25 a=0.45 b=1 | train_logloss=0.628825 train_brier=0.219398 | test_logloss=0.592735 test_brier=0.200788
H=35 K=25 a=0.45 b=1.05 | train_logloss=0.631612 train_brier=0.220357 | test_logloss=0.591535 test_brier=0.199760
H=35 K=25 a=0.475 b=0.9 | train_logloss=0.626518 train_brier=0.218569 | test_logloss=0.597511 test_brier=0.203509
H=35 K=25 a=0.475 b=0.95 | train_logloss=0.627225 train_brier=0.218827 | test_logloss=0.594804 test_brier=0.202035
H=35 K=25 a=0.475 b=1 | train_logloss=0.628894 train_brier=0.219418 | test_logloss=0.592831 test_brier=0.200791
H=35 K=25 a=0.475 b=1.05 | train_logloss=0.631722 train_brier=0.220386 | test_logloss=0.591773 test_brier=0.199817
H=35 K=25 a=0.5 b=0.9 | train_logloss=0.626537 train_brier=0.218579 | test_logloss=0.597351 test_brier=0.203410
H=35 K=25 a=0.5 b=0.95 | train_logloss=0.627290 train_brier=0.218852 | test_logloss=0.594800 test_brier=0.202000
H=35 K=25 a=0.5 b=1 | train_logloss=0.629003 train_brier=0.219454 | test_logloss=0.592981 test_brier=0.200816
H=35 K=25 a=0.5 b=1.05 | train_logloss=0.631875 train_brier=0.220432 | test_logloss=0.592071 test_brier=0.199898

=== WALKFORWARD: train=2015-2020 test=2021 ===
H=25 K=15 a=0.425 b=0.9 | train_logloss=0.629190 train_brier=0.219437 | test_logloss=0.612088 test_brier=0.212303
H=25 K=15 a=0.425 b=0.95 | train_logloss=0.627305 train_brier=0.218637 | test_logloss=0.609629 test_brier=0.211499
H=25 K=15 a=0.425 b=1 | train_logloss=0.625959 train_brier=0.218065 | test_logloss=0.607874 test_brier=0.211033
H=25 K=15 a=0.425 b=1.05 | train_logloss=0.625260 train_brier=0.217751 | test_logloss=0.606970 test_brier=0.210946
H=25 K=15 a=0.45 b=0.9 | train_logloss=0.628949 train_brier=0.219336 | test_logloss=0.611484 test_brier=0.212069
H=25 K=15 a=0.45 b=0.95 | train_logloss=0.627116 train_brier=0.218559 | test_logloss=0.609139 test_brier=0.211318
H=25 K=15 a=0.45 b=1 | train_logloss=0.625826 train_brier=0.218011 | test_logloss=0.607502 test_brier=0.210901
H=25 K=15 a=0.45 b=1.05 | train_logloss=0.625188 train_brier=0.217720 | test_logloss=0.606723 test_brier=0.210863
H=25 K=15 a=0.475 b=0.9 | train_logloss=0.628738 train_brier=0.219251 | test_logloss=0.610929 test_brier=0.211860
H=25 K=15 a=0.475 b=0.95 | train_logloss=0.626961 train_brier=0.218498 | test_logloss=0.608703 test_brier=0.211162
H=25 K=15 a=0.475 b=1 | train_logloss=0.625729 train_brier=0.217973 | test_logloss=0.607193 test_brier=0.210799
H=25 K=15 a=0.475 b=1.05 | train_logloss=0.625155 train_brier=0.217706 | test_logloss=0.606547 test_brier=0.210812
H=25 K=15 a=0.5 b=0.9 | train_logloss=0.628558 train_brier=0.219180 | test_logloss=0.610426 test_brier=0.211677
H=25 K=15 a=0.5 b=0.95 | train_logloss=0.626840 train_brier=0.218453 | test_logloss=0.608326 test_brier=0.211035
H=25 K=15 a=0.5 b=1 | train_logloss=0.625670 train_brier=0.217952 | test_logloss=0.606953 test_brier=0.210727
H=25 K=15 a=0.5 b=1.05 | train_logloss=0.625162 train_brier=0.217710 | test_logloss=0.606445 test_brier=0.210792
H=25 K=20 a=0.425 b=0.9 | train_logloss=0.626337 train_brier=0.218236 | test_logloss=0.608169 test_brier=0.211123
H=25 K=20 a=0.425 b=0.95 | train_logloss=0.625530 train_brier=0.217878 | test_logloss=0.607077 test_brier=0.210954
H=25 K=20 a=0.425 b=1 | train_logloss=0.625466 train_brier=0.217801 | test_logloss=0.606926 test_brier=0.211181
H=25 K=20 a=0.425 b=1.05 | train_logloss=0.626306 train_brier=0.218045 | test_logloss=0.607865 test_brier=0.211836
H=25 K=20 a=0.45 b=0.9 | train_logloss=0.626192 train_brier=0.218176 | test_logloss=0.607774 test_brier=0.210981
H=25 K=20 a=0.45 b=0.95 | train_logloss=0.625443 train_brier=0.217840 | test_logloss=0.606801 test_brier=0.210859
H=25 K=20 a=0.45 b=1 | train_logloss=0.625435 train_brier=0.217783 | test_logloss=0.606774 test_brier=0.211132
H=25 K=20 a=0.45 b=1.05 | train_logloss=0.626330 train_brier=0.218045 | test_logloss=0.607841 test_brier=0.211829
H=25 K=20 a=0.475 b=0.9 | train_logloss=0.626082 train_brier=0.218132 | test_logloss=0.607437 test_brier=0.210866
H=25 K=20 a=0.475 b=0.95 | train_logloss=0.625392 train_brier=0.217819 | test_logloss=0.606591 test_brier=0.210795
H=25 K=20 a=0.475 b=1 | train_logloss=0.625444 train_brier=0.217783 | test_logloss=0.606698 test_brier=0.211115
H=25 K=20 a=0.475 b=1.05 | train_logloss=0.626398 train_brier=0.218064 | test_logloss=0.607892 test_brier=0.211853
H=25 K=20 a=0.5 b=0.9 | train_logloss=0.626008 train_brier=0.218105 | test_logloss=0.607164 test_brier=0.210781
H=25 K=20 a=0.5 b=0.95 | train_logloss=0.625379 train_brier=0.217815 | test_logloss=0.606452 test_brier=0.210761
H=25 K=20 a=0.5 b=1 | train_logloss=0.625494 train_brier=0.217801 | test_logloss=0.606696 test_brier=0.211129

,train_start,train_end,test_year,best_H,best_K,best_a,best_b,train_logloss,test_logloss,train_brier,test_brier
0,2015,2019,2020,25,25,0.425,1.05,0.634830,0.589916,0.221704,0.199429
1,2015,2020,2021,30,25,0.500,0.90,0.624223,0.606307,0.217288,0.210808
2,2015,2021,2022,30,15,0.500,1.00,0.621901,0.610980,0.216432,0.211836
3,2015,2022,2023,25,20,0.425,1.00,0.621440,0.599913,0.216315,0.206276
4,2015,2023,2024,35,25,0.425,0.95,0.617582,0.595169,0.214518,0.202694

In [10]:
all_res = pd.concat(all_step_results, ignore_index=True)

# Mean test_logloss across heldout years for each hyperparameter tuple
tuple_means = (
    all_res
    .groupby(["H", "K", "a", "b"], as_index=False)
    .agg(
        mean_test_logloss=("test_logloss", "mean"),
        mean_test_brier=("test_brier", "mean"),
        n_steps=("heldout_year", "nunique"),
    )
    .sort_values(["mean_test_logloss", "mean_test_brier"], ascending=True)
    .reset_index(drop=True)
)

tuple_means.head(30)

     H   K      a     b  mean_test_logloss  mean_test_brier  n_steps
0   25  20  0.425  1.00           0.602027         0.207139        5
1   25  20  0.450  1.00           0.602076         0.207161        5
2   25  25  0.425  0.95           0.602081         0.207127        5
3   25  20  0.425  1.05           0.602099         0.207072        5
4   30  20  0.425  1.00           0.602143         0.207178        5
5   25  25  0.450  0.95           0.602153         0.207155        5
6   30  25  0.425  0.95           0.602185         0.207158        5
7   30  20  0.425  1.05           0.602192         0.207092        5
8   25  20  0.475  1.00           0.602193         0.207210        5
9   30  20  0.450  1.00           0.602194         0.207199        5
10  25  20  0.450  1.05           0.602254         0.207130        5
11  30  25  0.450  0.95           0.602260         0.207186        5
12  25  25  0.475  0.95           0.602291         0.207209        5
13  30  20  0.475  1.00           0.602310         0.207246        5
14  30  20  0.450  1.05           0.602347         0.207148        5
15  25  20  0.500  1.00           0.602377         0.207286        5
16  30  25  0.475  0.95           0.602401         0.207239        5
17  35  20  0.425  1.00           0.602441         0.207297        5
18  35  20  0.425  1.05           0.602476         0.207193        5
19  35  25  0.425  0.95           0.602476         0.207270        5
20  25  20  0.475  1.05           0.602478         0.207214        5
21  35  20  0.450  1.00           0.602490         0.207314        5
22  30  20  0.500  1.00           0.602493         0.207319        5
23  25  25  0.450  0.90           0.602500         0.207366        5
24  25  25  0.500  0.95           0.602501         0.207291        5
25  25  25  0.425  0.90           0.602529         0.207374        5
26  25  25  0.475  0.90           0.602535         0.207383        5
27  25  15  0.450  1.05           0.602539         0.207399        5
28  35  25  0.450  0.95           0.602551         0.207295        5
29  25  15  0.425  1.05           0.602554         0.207398        5